---
http_interactions:
- request:
    method: get
    uri: https://api.os.uk/search/places/v1/postcode?key=<ORDNANACE_SURVEY_API_KEY>&lr=EN&postcode=SW1H9EA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v1.0.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 09 Dec 2020 10:54:16 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Tx-Id:
      - 1607511256789:789
      Status:
      - success
    body:
      encoding: UTF-8
      string: |-
        {
          "header" : {
            "uri" : "https://api.os.uk/search/places/v1/postcode?lr=EN&postcode=SW1H9EA",
            "query" : "postcode=SW1H9EA",
            "offset" : 0,
            "totalresults" : 4,
            "format" : "JSON",
            "dataset" : "DPA",
            "lr" : "EN",
            "maxresults" : 100,
            "epoch" : "80",
            "output_srs" : "EPSG:27700"
          },
          "results" : [ {
            "DPA" : {
              "UPRN" : "100023337883",
              "UDPRN" : "23749699",
              "ADDRESS" : "SUPER FIRM LTD, 84, PETTY FRANCE, LONDON, SW1H 9EA",
              "ORGANISATION_NAME" : "SUPER FIRM LTD",
              "BUILDING_NUMBER" : "84",
              "THOROUGHFARE_NAME" : "PETTY FRANCE",
              "POST_TOWN" : "LONDON",
              "POSTCODE" : "SW1H 9EA",
              "RPC" : "2",
              "X_COORDINATE" : 529526.39,
              "Y_COORDINATE" : 179490.43,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "CR07",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Restaurant / Cafeteria",
              "LOCAL_CUSTODIAN_CODE" : 5990,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "CITY OF WESTMINSTER",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE" : "2",
              "BLPU_STATE_CODE_DESCRIPTION" : "In use",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000042216527",
              "LAST_UPDATE_DATE" : "10/02/2016",
              "ENTRY_DATE" : "19/03/2001",
              "BLPU_STATE_DATE" : "19/03/2001",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100023337884",
              "UDPRN" : "23749702",
              "ADDRESS" : "TRANSPORT FOR LONDON, 98, PETTY FRANCE, LONDON, SW1H 9EA",
              "ORGANISATION_NAME" : "TRANSPORT FOR LONDON",
              "BUILDING_NUMBER" : "98",
              "THOROUGHFARE_NAME" : "PETTY FRANCE",
              "POST_TOWN" : "LONDON",
              "POSTCODE" : "SW1H 9EA",
              "RPC" : "2",
              "X_COORDINATE" : 529558.47,
              "Y_COORDINATE" : 179482.17,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "CO01",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Office / Work Studio",
              "LOCAL_CUSTODIAN_CODE" : 5990,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "CITY OF WESTMINSTER",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE" : "2",
              "BLPU_STATE_CODE_DESCRIPTION" : "In use",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000042217066",
              "LAST_UPDATE_DATE" : "29/04/2020",
              "ENTRY_DATE" : "19/03/2001",
              "BLPU_STATE_DATE" : "19/03/2001",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "100023337882",
              "UDPRN" : "23749700",
              "ADDRESS" : "100, PETTY FRANCE, LONDON, SW1H 9EA",
              "BUILDING_NUMBER" : "100",
              "THOROUGHFARE_NAME" : "PETTY FRANCE",
              "POST_TOWN" : "LONDON",
              "POSTCODE" : "SW1H 9EA",
              "RPC" : "2",
              "X_COORDINATE" : 529619.99,
              "Y_COORDINATE" : 179499.2,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "RD",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Dwelling",
              "LOCAL_CUSTODIAN_CODE" : 5990,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "CITY OF WESTMINSTER",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE" : "2",
              "BLPU_STATE_CODE_DESCRIPTION" : "In use",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000042216526",
              "LAST_UPDATE_DATE" : "12/11/2018",
              "ENTRY_DATE" : "19/03/2001",
              "BLPU_STATE_DATE" : "19/03/2001",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          }, {
            "DPA" : {
              "UPRN" : "10033648845",
              "UDPRN" : "54770395",
              "ADDRESS" : "C P S, 102, PETTY FRANCE, LONDON, SW1H 9EA",
              "ORGANISATION_NAME" : "C P S",
              "BUILDING_NUMBER" : "102",
              "THOROUGHFARE_NAME" : "PETTY FRANCE",
              "POST_TOWN" : "LONDON",
              "POSTCODE" : "SW1H 9EA",
              "RPC" : "2",
              "X_COORDINATE" : 529576.0,
              "Y_COORDINATE" : 179549.0,
              "STATUS" : "APPROVED",
              "LOGICAL_STATUS_CODE" : "1",
              "CLASSIFICATION_CODE" : "CO01",
              "CLASSIFICATION_CODE_DESCRIPTION" : "Office / Work Studio",
              "LOCAL_CUSTODIAN_CODE" : 5990,
              "LOCAL_CUSTODIAN_CODE_DESCRIPTION" : "CITY OF WESTMINSTER",
              "POSTAL_ADDRESS_CODE" : "D",
              "POSTAL_ADDRESS_CODE_DESCRIPTION" : "A record which is linked to PAF",
              "BLPU_STATE_CODE" : "2",
              "BLPU_STATE_CODE_DESCRIPTION" : "In use",
              "TOPOGRAPHY_LAYER_TOID" : "osgb1000001796535716",
              "PARENT_UPRN" : "10033604583",
              "LAST_UPDATE_DATE" : "06/07/2020",
              "ENTRY_DATE" : "15/06/2020",
              "BLPU_STATE_DATE" : "15/06/2020",
              "LANGUAGE" : "EN",
              "MATCH" : 1.0,
              "MATCH_DESCRIPTION" : "EXACT"
            }
          } ]
        }
  recorded_at: Wed, 09 Dec 2020 10:54:16 GMT
- request:
    method: post
    uri: https://benefitchecker.stg.legalservices.gov.uk/lsx/lsc-services/benefitChecker?wsdl
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsdl="https://lsc.gov.uk/benefitchecker/service/1.0/API_1.0_Check"
        xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><wsdl:check><clientReference>dc5e224a-badd-4fbe-ab5b-dc8c252a108b</clientReference><nino>CB987654A</nino><surname>USER</surname><dateOfBirth>19990403</dateOfBirth><dateOfAward>20201209</dateOfAward><lscServiceName><BC_LSC_SERVICE_NAME></lscServiceName><clientOrgId><BC_CLIENT_ORG_ID></clientOrgId><clientUserId><BC_CLIENT_USER_ID></clientUserId></wsdl:check></env:Body></env:Envelope>
    headers:
      Soapaction:
      - '"check"'
      Content-Type:
      - text/xml;charset=UTF-8
      Content-Length:
      - '649'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: ''
    headers:
      Date:
      - Wed, 09 Dec 2020 10:54:19 GMT
      Content-Type:
      - text/xml;charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Amzn-Trace-Id:
      - Root=1-5fd0acdb-569c74163de411b460c4b7ce;
      Vary:
      - Accept-Encoding
    body:
      encoding: ASCII-8BIT
      string: <?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><benefitCheckerResponse
        xmlns="https://lsc.gov.uk/benefitchecker/service/1.0/API_1.0_Check"><ns1:originalClientRef
        xmlns:ns1="http://lsc.gov.uk/benefitchecker/data/1.0">dc5e224a-badd-4fbe-ab5b-dc8c252a108b</ns1:originalClientRef><ns2:benefitCheckerStatus
        xmlns:ns2="http://lsc.gov.uk/benefitchecker/data/1.0">Undetermined</ns2:benefitCheckerStatus><ns3:confirmationRef
        xmlns:ns3="http://lsc.gov.uk/benefitchecker/data/1.0">T1607511259795</ns3:confirmationRef></benefitCheckerResponse></soapenv:Body></soapenv:Envelope>
  recorded_at: Wed, 09 Dec 2020 10:54:19 GMT
recorded_with: VCR 6.0.0
