---
http_interactions:
- request:
    method: get
    uri: https://laa-provider-details-api-uat.apps.live.cloud-platform.service.justice.gov.uk/provider-offices/0X395U/schedules
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      X-Authorization:
      - "<PDA_AUTH_KEY>"
      User-Agent:
      - Faraday v2.13.4
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: ''
    headers:
      Date:
      - Wed, 13 Aug 2025 14:04:38 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Request-Id:
      - e088eb0d-a83c-4365-bfa0-bbf88b733037
      Request-Handler:
      - laa-pda-api-deployment-6d99c67c96-g4284
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - '0'
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Pragma:
      - no-cache
      Expires:
      - '0'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: '{"firm":{"firmNumber":"1639","firmId":1639,"ccmsFirmId":19148,"parentFirmId":0,"firmName":"DAVID
        GRAY LLP","firmType":"Legal Services Provider","constitutionalStatus":"LLP","solicitorAdvocateYN":null,"advocateLevel":null,"barCouncilRoll":null,"companyHouseNumber":null},"office":{"firmOfficeId":4545,"ccmsFirmOfficeId":137570,"firmOfficeCode":"0X395U","officeName":"0X395U,OLD
        COUNTY COURT","officeCodeAlt":"DAVID GRAY LLP","type":"Legal Services Supplier
        (Civil/Crime/Both/Mediator)"},"pds":false,"schedules":[{"contractType":"Standard","contractDescription":"2024
        Standard Civil Contract","contractNumber":"1034798","contractReference":"01/0X395U/2024/1","contractStatus":"Open","contractAuthorizationStatus":"APPROVED","contractStartDate":"2024-09-01","contractEndDate":"2026-06-30","areaOfLaw":"LEGAL
        HELP","scheduleType":"Standard","scheduleNumber":"0X395U/2024/01","scheduleContractNumber":"1034798","scheduleContractReference":"01/0X395U/2024/1","scheduleAuthorizationStatus":"APPROVED","scheduleStatus":"Open","scheduleStartDate":"2024-09-01","scheduleEndDate":"2025-08-31","scheduleLines":[{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"AAP","description":"Legal Help (Civil).Claims Against
        Public Authorities","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"COM","description":"Legal Help (Civil).Community Care","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"CON","description":"Legal Help (Civil).Consumer General
        Contract","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"DEB","description":"Legal Help (Civil).Debt","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"DISC","description":"Legal Help (Civil).Discrimination","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"EDU","description":"Legal Help (Civil).Education","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"EMP","description":"Legal Help (Civil).Employment","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"HOU","description":"Legal Help (Civil).Housing","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"IMMAS","description":"Legal Help (Civil).Immigration
        - Asylum","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"IMMOT","description":"Legal Help (Civil).Immigration","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"MAT","description":"Legal Help (Civil).Family","devolvedPowersStatus":"Yes
        - Excluding JR Proceedings","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"N/A","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"1","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"MED","description":"Legal Help (Civil).Clinical Negligence","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"MHE","description":"Legal Help (Civil).Mental Health","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"MSC","description":"Legal Help (Civil).Residual(Miscellaneous)","devolvedPowersStatus":"Yes
        - Excluding JR Proceedings","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"N/A","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"1","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"PI","description":"Legal Help (Civil).Personal Injury","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"PUB","description":"Legal Help (Civil).Public Law","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"WB","description":"Legal Help (Civil).Welfare Benefits","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null},{"areaOfLaw":"LEGAL
        HELP","categoryOfLaw":"ELA","description":"Legal Help (Civil).Early Legal
        Advice","devolvedPowersStatus":"No","dpTypeOfChange":null,"dpReasonForChange":null,"dpDateOfChange":null,"remainderWorkFlag":"No","minimumCasesAllowedCount":"0","maximumCasesAllowedCount":"0","minimumToleranceCount":"0","maximumToleranceCount":"0","minimumLicenseCount":"0","maximumLicenseCount":"0","workInProgressCount":"0","outreach":null,"cancelFlag":"N","cancelReason":null,"cancelDate":null,"closedDate":null,"closedReason":null}],"nmsAuths":[]}]}'
  recorded_at: Wed, 13 Aug 2025 14:04:38 GMT
- request:
    method: get
    uri: https://laa-provider-details-api-uat.apps.live.cloud-platform.service.justice.gov.uk/provider-users/System%20Tester
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      X-Authorization:
      - "<PDA_AUTH_KEY>"
      User-Agent:
      - Faraday v2.13.4
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 204
      message: ''
    headers:
      Date:
      - Wed, 13 Aug 2025 14:04:38 GMT
      Connection:
      - keep-alive
      Request-Id:
      - 1505bf22-1061-441c-a450-8035ff1b382b
      Request-Handler:
      - laa-pda-api-deployment-6d99c67c96-mzqkq
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - '0'
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Pragma:
      - no-cache
      Expires:
      - '0'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Frame-Options:
      - DENY
    body:
      encoding: UTF-8
      string: ''
  recorded_at: Wed, 13 Aug 2025 14:04:38 GMT
recorded_with: VCR 6.3.1
