---
http_interactions:
- request:
    method: get
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/client_involvement_types
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.3
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 03 Feb 2023 12:21:10 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '277'
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"8bf337339345d42d16a9e6062fb65ccf"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 22549e1c1c02490802f58f8bf8648fd5
      X-Runtime:
      - '0.004267'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '[{"ccms_code":"A","description":"Applicant/claimant/petitioner"},{"ccms_code":"D","description":"Defendant/respondent"},{"ccms_code":"W","description":"Subject
        of proceedings (child)"},{"ccms_code":"I","description":"Intervenor"},{"ccms_code":"Z","description":"Joined
        party"}]'
  recorded_at: Fri, 03 Feb 2023 12:21:10 GMT
- request:
    method: get
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/client_involvement_types
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.3
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 03 Feb 2023 12:21:11 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '277'
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"8bf337339345d42d16a9e6062fb65ccf"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 2cd200389bce3d49888f3716e23ae954
      X-Runtime:
      - '0.005479'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '[{"ccms_code":"A","description":"Applicant/claimant/petitioner"},{"ccms_code":"D","description":"Defendant/respondent"},{"ccms_code":"W","description":"Subject
        of proceedings (child)"},{"ccms_code":"I","description":"Intervenor"},{"ccms_code":"Z","description":"Joined
        party"}]'
  recorded_at: Fri, 03 Feb 2023 12:21:10 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/proceeding_type_defaults
    body:
      encoding: UTF-8
      string: '{"proceeding_type_ccms_code":"DA001","delegated_functions_used":false,"client_involvement_type":"A"}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.3
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 03 Feb 2023 12:21:11 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '708'
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"738a2e1692d7caa18f9ac20fab29e586"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 9b12c4427a2914c44a17690b6e967f05
      X-Runtime:
      - '0.015582'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"success":true,"requested_params":{"proceeding_type_ccms_code":"DA001","delegated_functions_used":false,"client_involvement_type":"A"},"default_level_of_service":{"level":3,"name":"Full
        Representation","stage":8},"default_scope":{"code":"AA019","meaning":"Injunction
        FLA-to final hearing","description":"As to proceedings under Part IV Family
        Law Act 1996 limited to all steps up to and including obtaining and serving
        a final order and in the event of breach leading to the exercise of a power
        of arrest to representation on the consideration of the breach by the court
        (but excluding applying for a warrant of arrest, if not attached, and representation
        in contempt proceedings).","additional_params":[]}}'
  recorded_at: Fri, 03 Feb 2023 12:21:11 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/proceeding_type_defaults
    body:
      encoding: UTF-8
      string: '{"proceeding_type_ccms_code":"DA001","delegated_functions_used":false,"client_involvement_type":"A"}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.3
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 03 Feb 2023 12:21:12 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '708'
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"738a2e1692d7caa18f9ac20fab29e586"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 48b9e01d0b45468cf95daa83a2f583eb
      X-Runtime:
      - '0.014967'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"success":true,"requested_params":{"proceeding_type_ccms_code":"DA001","delegated_functions_used":false,"client_involvement_type":"A"},"default_level_of_service":{"level":3,"name":"Full
        Representation","stage":8},"default_scope":{"code":"AA019","meaning":"Injunction
        FLA-to final hearing","description":"As to proceedings under Part IV Family
        Law Act 1996 limited to all steps up to and including obtaining and serving
        a final order and in the event of breach leading to the exercise of a power
        of arrest to representation on the consideration of the breach by the court
        (but excluding applying for a warrant of arrest, if not attached, and representation
        in contempt proceedings).","additional_params":[]}}'
  recorded_at: Fri, 03 Feb 2023 12:21:11 GMT
recorded_with: VCR 6.1.0
