---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
    exclude:
      - '**/app/views/layouts/_google_tag_manager.html.erb'
  HardCodedString:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Style/NumericPredicate:
        Exclude:
          - 'app/views/providers/vehicles/remaining_payments/show.html.erb'
