CommitMsg:
  ALL:
    requires_files: false
    quiet: true

  CapitalizedSubject:
    enabled: false

  SingleLineSubject:
    enabled: false

  TextWidth:
    enabled: false

  TrailingPeriod:
    enabled: false

PreCommit:
  Prek:
    enabled: true
    command: ['prek', 'run']
    requires_files: true
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop'] # Invoke within Bundler context
    requires_files: true
  ErbLint:
    enabled: true
    command: ['erblint']
    requires_files: true
  StandardJS:
    enabled: true
    command: ['yarn', 'run', 'standard']
    requires_files: true
    include: 'app/javascript/**/*.js'
  StyleLint:
    enabled: true
    command: ['yarn', 'run', 'stylelint']
    requires_files: true
    include: 'app/assets/stylesheets/**/*.scss'
  DBAnonymizer:
    enabled: true
    command: ['ruby', './scripts/migration_hook.rb']
    requires_files: true
    include: 'db/migrate/*.rb'
