require:
  - rubocop-performance

inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - 'db/schema.rb'
  - 'db/data_schema.rb'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'ccms_integration/*'
  - 'tmp/**/*'
  - 'log/**/*'
  - 'db/migrate/[2018-2022]*'

Lint/AmbiguousBlockAssociation:
  Exclude:
  - 'spec/**/*'
