require:
  - rubocop-performance

inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - 'db/schema.rb'
  - 'db/data_schema.rb'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'ccms_integration/*'
  - 'tmp/**/*'
  - 'log/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
  - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
  - 'db/migrate/*'
  - 'ccms_integration/helpers/ccms_payload_analyser.rb'
  - 'bin/bundle'

Metrics/BlockLength:
  Exclude:
  - 'config/routes.rb'
  - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/services/reports/mis/application_detail_csv_line.rb'
    - 'app/models/legal_aid_application.rb'

Metrics/MethodLength:
  Exclude:
  - 'db/migrate/*'
  - 'ccms_integration/helpers/ccms_payload_analyser.rb'
  - 'spec/**/*'
  - 'app/services/reports/mis/application_detail_csv_line.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  IgnoredMethods:
    - 'cli_arg_version' # from bin/bundle - auto generated method

Metrics/PerceivedComplexity:
  IgnoredMethods:
    - 'cli_arg_version' # from bin/bundle - auto generated method
