require: 
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'ccms_integration/*'
  - 'tmp/**/*'
  - 'log/**/*'

Layout/LineLength:
  Max: 180

Lint/AmbiguousBlockAssociation:
  Exclude:
  - 'spec/**/*'

Lint/UriEscapeUnescape:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/AbcSize:
  Exclude:
  - 'db/migrate/*'
  - 'ccms_integration/helpers/ccms_payload_analyser.rb'
  - 'bin/bundle'

Metrics/BlockLength:
  Exclude:
  - 'config/routes.rb'
  - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/services/reports/mis/application_detail_csv_line.rb'
    - 'app/models/legal_aid_application.rb'

Metrics/MethodLength:
  Exclude:
  - 'db/migrate/*'
  - 'ccms_integration/helpers/ccms_payload_analyser.rb'
  - 'spec/**/*'
  - 'app/services/reports/mis/application_detail_csv_line.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 7

Rails/Present:
  Exclude:
  - 'bin/bundle'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Exclude:
  - '**/*'

Style/SymbolArray:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/CyclomaticComplexity:
  IgnoredMethods:
    - 'cli_arg_version' # from bin/bundle - auto generated method

Style/AccessorGrouping:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Metrics/PerceivedComplexity:
  IgnoredMethods:
    - 'cli_arg_version' # from bin/bundle - auto generated method
