require: rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'ccms_integration/*'

Layout/LineLength:
  Max: 180

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
  - 'spec/**/*'

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/AbcSize:
  Exclude:
  - 'db/migrate/*'
  - 'ccms_integration/helpers/ccms_payload_analyser.rb'
  - 'bin/bundle'

Metrics/BlockLength:
  Exclude:
  - 'config/routes.rb'
  - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/services/reports/mis/application_detail_csv_line.rb'
    - 'app/models/legal_aid_application.rb'

Metrics/MethodLength:
  Exclude:
  - 'db/migrate/*'
  - 'ccms_integration/helpers/ccms_payload_analyser.rb'
  - 'spec/**/*'
  - 'app/services/reports/mis/application_detail_csv_line.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 7

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Exclude:
  - '**/*'

Style/SymbolArray:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/CyclomaticComplexity:
  IgnoredMethods:
    - 'cli_arg_version' # from bin/bundle - auto generated method

Style/AccessorGrouping:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: false

Metrics/PerceivedComplexity:
  IgnoredMethods:
    - 'cli_arg_version' # from bin/bundle - auto generated method
