inherit_from: .rubocop_todo.yml

require: rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - 'ccms_integration/*'
    - 'log/**/*'
    - 'db/migrate/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
  - 'spec/**/*'

Style/ZeroLengthPredicate:
  Exclude:
    - app/controllers/status_controller.rb

FactoryBot/FactoryAssociationWithStrategy:
  Exclude:
    - spec/factories/legal_aid_applications.rb # Too many traits create objects that loop back

RSpec/IndexedLet:
  Max: 2
  Exclude:
    - spec/services/cfe/* # due to be deleted soon 🤞
