# important to continue using node-modules for rails, as zero-install does not work well with the way rails expects to find its assets,
# and it also does not work well with docker builds, which rely on caching node_modules in the image layers, and it also does not work
# well with CI caching, which also relies on caching node_modules.
nodeLinker: node-modules

# use a deterministic version of yarn, to ensure consistent installs across environments, and to avoid issues with global yarn versions
yarnPath: .yarn/releases/yarn-4.12.0.cjs

# default, but for rails we do not want to create or store a project cache in the repository, we rely on the global cache and the node_modules in the docker image
enableGlobalCache: true 

# Ensure consistent installs, fail if lockfile is out of sync, both loccally, in CI and in docker builds
# WARNING: Will need to be disabled temporarily to update lockfile.
enableImmutableInstalls: true

# Disable all lifecycle scripts for security reasons, namely to mitigate against shai-hulud v2.0 attacks
enableScripts: false 
