version: '3'

services:
  postgres:
    image: postgres:11.6
    volumes:
    - pgdata:/var/lib/postgresql/data
  clamav:
    image: ghcr.io/ministryofjustice/hmpps-clamav:sha-0ae98e9
    ports:
    - "3310:3310"
  web:
    environment:
    - DB_HOST=postgres
    build: .
    command: docker/run
    ports:
    - "3002:3002"
    depends_on:
    - postgres
    - clamav

volumes:
  pgdata:
