module Flow
  module Flows
    class ProviderMerits
      STEPS = {
        start_involved_children_task: Steps::ProviderMerits::StartInvolvedChildrenTaskStep,
        involved_children: Steps::ProviderMerits::InvolvedChildrenStep,
        has_other_involved_children: Steps::ProviderMerits::HasOtherInvolvedChildrenStep,
        remove_involved_child: Steps::ProviderMerits::RemoveInvolvedChildStep,
        date_client_told_incidents: Steps::ProviderMerits::DateClientToldIncidentsStep,
        when_contact_was_made: Steps::ProviderMerits::WhenContactWasMadeStep,
        opponent_individuals: Steps::ProviderMerits::OpponentIndividualsStep,
        opponent_existing_organisations: Steps::ProviderMerits::OpponentExistingOrganisationsStep,
        opponent_new_organisations: Steps::ProviderMerits::OpponentNewOrganisationStep,
        start_opponent_task: Steps::ProviderMerits::StartOpponentTaskStep,
        opponent_types: Steps::ProviderMerits::OpponentTypesStep,
        has_other_opponents: Steps::ProviderMerits::HasOtherOpponentsStep,
        opponents_mental_capacities: Steps::ProviderMerits::OpponentsMentalCapacitiesStep,
        court_order_copies: Steps::ProviderMerits::CourtOrderCopiesStep,
        domestic_abuse_summaries: Steps::ProviderMerits::DomesticAbuseSummariesStep,
        statement_of_cases: Steps::ProviderMerits::StatementOfCasesStep,
        statement_of_case_uploads: Steps::ProviderMerits::StatementOfCaseUploadsStep,
        client_denial_of_allegations: Steps::ProviderMerits::ClientDenialOfAllegationsStep,
        client_offered_undertakings: Steps::ProviderMerits::ClientOfferedUndertakingsStep,
        in_scope_of_laspos: Steps::ProviderMerits::InScopeOfLasposStep,
        is_matter_opposed: Steps::ProviderMerits::IsMatterOpposedStep,
        nature_of_urgencies: Steps::ProviderMerits::NatureOfUrgenciesStep,
        matter_opposed_reasons: Steps::ProviderMerits::MatterOpposedReasonsStep,
        second_appeals: Steps::ProviderMerits::SecondAppealsStep,
        second_appeal_court_types: Steps::ProviderMerits::SecondAppealCourtTypesStep,
        first_appeal_court_types: Steps::ProviderMerits::FirstAppealCourtTypesStep,
        original_judge_levels: Steps::ProviderMerits::OriginalJudgeLevelsStep,
        chances_of_success: Steps::ProviderMerits::ChancesOfSuccessStep,
        opponents_application: Steps::ProviderMerits::OpponentsApplicationStep,
        attempts_to_settle: Steps::ProviderMerits::AttemptsToSettleStep,
        prohibited_steps: Steps::ProviderMerits::ProhibitedStepsStep,
        linked_children: Steps::ProviderMerits::LinkedChildrenStep,
        specific_issue: Steps::ProviderMerits::SpecificIssueStep,
        vary_order: Steps::ProviderMerits::VaryOrderStep,
        child_care_assessments: Steps::ProviderMerits::ChildCareAssessmentStep,
        child_care_assessment_results: Steps::ProviderMerits::ChildCareAssessmentResultStep,
        application_merits_task_client_is_biological_parent: Steps::ProviderApplicationMerits::IsBiologicalParentStep,
        application_merits_task_client_has_parental_responsibilities: Steps::ProviderApplicationMerits::ParentalResponsibilitiesStep,
        application_merits_task_client_is_child_subject: Steps::ProviderApplicationMerits::ChildIsSubjectStep,
        application_merits_task_client_check_parental_answers: Steps::ProviderApplicationMerits::ClientCheckParentalAnswersStep,
        merits_task_lists: Steps::ProviderMerits::MeritsTaskListsStep,
        uploaded_evidence_collections: Steps::ProviderMerits::UploadedEvidenceCollectionsStep,
        check_merits_answers: Steps::ProviderMerits::CheckMeritsAnswersStep,
        confirm_client_declarations: Steps::ProviderMerits::ConfirmClientDeclarationsStep,
        review_and_print_applications: Steps::ProviderMerits::ReviewAndPrintApplicationsStep,
        end_of_applications: Steps::ProviderMerits::EndOfApplicationsStep,
        submitted_applications: Steps::ProviderMerits::SubmittedApplicationsStep,
        merits_reports: Steps::ProviderMerits::MeritsReportsStep,
      }.freeze
    end
  end
end
