name: 'Delete UAT deployment'
description: 'Deletes a UAT deployment with a name mathcing the merged/closed branch'
outputs:
  branch-name:
  description: "Extracted branch name"
  value: ${{ steps.extract_branch.outputs.branch }}
  release-name:
  description: "Extracted release name"
  value: ${{ steps.extract_release.outputs.release }}
runs:
  using: "composite"
  shell: bash
  steps:
    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: |
        if [ $GITHUB_EVENT_NAME == "pull_request" ]
        then
          branch=$GITHUB_HEAD_REF
        else
          branch=${GITHUB_REF#refs/heads/}
        fi

        echo "##[set-output name=branch;]$(echo $branch)"

    - name: Extract release name
      id: extract_release
      shell: bash
      run: |
        branch=${{ steps.extract_branch.outputs.branch }}
        truncated_branch=$(echo $branch | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | cut -c1-30 | sed 's/-$//')
        echo "##[set-output name=release;]$(echo "apply-${truncated_branch}")"

    - name: Authenticate to the cluster
      id: authenticate_to_cluster
      shell: bash
      env:
        K8S_CLUSTER: ${{ secrets.K8S_CLUSTER_NAME_LIVE }}
        K8S_CLUSTER_CERT: ${{ secrets.K8S_CLUSTER_CERT_LIVE }}
        K8S_NAMESPACE: ${{ secrets.K8S_UAT_NAMESPACE }}
        K8S_TOKEN: ${{ secrets.K8S_UAT_TOKEN_LIVE }}
      run: |
        echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
        kubectl config set-cluster ${K8S_CLUSTER} --certificate-authority=./ca.crt --server=https://${K8S_CLUSTER}
        kubectl config set-credentials circleci --token=${K8S_TOKEN}
        kubectl config set-context ${K8S_CLUSTER} --cluster=${K8S_CLUSTER} --user=circleci --namespace=${K8S_NAMESPACE}
        kubectl config use-context ${K8S_CLUSTER}

    - name: Delete UAT release
      id: delete_release
      shell: bash
      run: |
        release_name=${{ steps.extract_release.outputs.release }}
        found=$(helm list --all | grep $release_name)

        if [[ ! -z "$found" ]]
        then
          echo "Deleting UAT release ${release_name}..."
          helm delete $release_name
        else
          echo "UAT release, ${release_name}, not found!"
        fi
