apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name | trunc 26 }}-destroy-purgeable
  labels:
    app: {{ template "apply-for-legal-aid.name" . }}-cron-destroy-purgeable
    chart: {{ template "apply-for-legal-aid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: '30 1 * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            reportuploader: cronjob
        spec:
          containers:
          - name: destroy-purgeable
            image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
            imagePullPolicy: IfNotPresent
            command: ['rake', "purge:destroy"]
{{ include "apply-for-legal-aid.envs" . | nindent 12 }}
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
          restartPolicy: Never
