apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name | trunc 26 }}-extract-digest
  labels:
    app: {{ template "apply-for-legal-aid.name" . }}
    chart: {{ template "apply-for-legal-aid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: '0 2 * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: {{ .Values.cronjobs_failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.jobs_backoffLimit | default 6 }}
      template:
        metadata:
          labels:
            reportuploader: cronjob
        spec:
          containers:
          - name: extract-digest
            image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
            imagePullPolicy: IfNotPresent
            command: ['rake', "digest:extract"]
{{ include "apply-for-legal-aid.envs" . | nindent 12 }}
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
          restartPolicy: Never
