{{- if eq .Values.env "production" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-submit-ccms-on
  labels:
    app: {{ template "apply-for-legal-aid.name" . }}
    chart: {{ template "apply-for-legal-aid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: '0 8 * * 2' # Every tuesday at 08:00
  timeZone: "Europe/London"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            reportuploader: cronjob
        spec:
          serviceAccountName: "{{ .Values.service_account.name }}"
          containers:
          - name: turn-on-ccms-submissions
            image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
            imagePullPolicy: IfNotPresent
            command: ['bin/rails', 'ccms_submissions:turn_on']
{{ include "apply-for-legal-aid.envs" . | nindent 12 }}
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop: [ "ALL" ]
          restartPolicy: Never
{{- end }}
