{{- $defaultStartHour := 1 }}
{{- $startHourOffset := include "apply-for-legal-aid.cronjob-hour-to-start-offset" . -}}
{{- $startHour := add $defaultStartHour $startHourOffset }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name | trunc 26 }}-mark-purgeable
  labels:
    app: {{ template "apply-for-legal-aid.name" . }}
    chart: {{ template "apply-for-legal-aid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: '0 {{ $startHour }} * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            reportuploader: cronjob
        spec:
          serviceAccountName: "{{ .Values.service_account.name }}"
          containers:
          - name: mark-purgeable
            image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
            imagePullPolicy: IfNotPresent
            command: ['rake', "purge:mark"]
{{ include "apply-for-legal-aid.envs" . | nindent 12 }}
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
            securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop: [ "ALL" ]
          restartPolicy: Never
