{{- if .Values.ingress.enabled -}}
{{- $fullName := include "apply-for-legal-aid.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $secretName := .Values.ingress.secretName -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "apply-for-legal-aid.name" . }}
    chart: {{ template "apply-for-legal-aid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.ingress.whitelist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ include "apply-for-legal-aid.whitelist" $ }}"
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  {{- range .Values.ingress.hosts }}
  - hosts:
    - {{ . }}
    secretName: {{ $secretName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    {{- end }}
{{- end }}
