{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "apply-for-legal-aid.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
  {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}  # end of first if statement
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "apply-for-legal-aid.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}  # end of range
      secretName: {{ .secretName }}
    {{- end }} # end of range
  {{- end }} # end of if statement about ingress or end of tls
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}  # end of range
    {{- end }}  # end of range
  {{- end }} # end of rules?