{{- if .Values.ingress.enabled -}}
{{- $fullName := include "apply-for-legal-aid.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "apply-for-legal-aid.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - "{{ .Values.host }}"
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
  {{- end }}