apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apply-for-legal-aid.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  secretKey: {{ .Values.deploy.secretKey | b64enc | quote }}
  railsMasterKey: {{ .Values.deploy.rails_master_key | b64enc | quote }}
  {{if .Values.postgresql.enabled }}
  postgresqlDatabase: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  postgresqlUsername: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresqlPassword: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{ end }}
  sentryDsn: {{ .Values.sentry.dsn | b64enc | quote }}
  govukNotifyApiKey: {{ .Values.govuk_notify.api_key | b64enc | quote }}
  ordnanaceSurveyApiKey: {{ .Values.ordnanace_survey.api_key | b64enc | quote }}
  benefitCheckerLscServiceName: {{ .Values.benefit_checker.lscServiceName | b64enc | quote }}
  benefitCheckerClientOrgId: {{ .Values.benefit_checker.clientOrgId | b64enc | quote }}
  benefitCheckerClientUserId: {{ .Values.benefit_checker.clientUserId | b64enc | quote }}
  benefitCheckerWsdlUrl: {{ .Values.benefit_checker.wsdlUrl | b64enc | quote }}
  ccmsSoaSubmitApplications: {{ .Values.ccms_soa.submit_applications | b64enc | quote }}
  ccmsSoaAwsGatewayApiKey: {{ .Values.ccms_soa.awsGatewayApiKey | b64enc | quote }}
  ccmsSoaClientUsername: {{ .Values.ccms_soa.clientUsername | b64enc | quote }}
  ccmsSoaClientPasswordType: {{ .Values.ccms_soa.clientPasswordType | b64enc | quote }}
  ccmsSoaClientPassword: {{ .Values.ccms_soa.clientPassword | b64enc | quote }}
  ccmsSoaUserRole: {{ .Values.ccms_soa.userRole | b64enc | quote }}
  ccmsSoaCaseServicesWsdl: {{ .Values.ccms_soa.caseServicesWsdl | b64enc | quote }}
  ccmsSoaClientProxyServiceWsdl: {{ .Values.ccms_soa.clientProxyServiceWsdl | b64enc | quote }}
  ccmsSoaDocumentServicesWsdl: {{ .Values.ccms_soa.documentServicesWsdl | b64enc | quote }}
  ccmsSoaGetReferenceDataWsdl: {{ .Values.ccms_soa.getReferenceDataWsdl | b64enc | quote }}
  geckoboardApiKey: {{ .Values.geckoboard.api_key | b64enc | quote }}
  laaPortalIdpSsoTargetUrl: {{ .Values.laa_portal.idpSsoTargetUrl | b64enc | quote }}
  laaPortalIdpSloTargetUrl: {{ .Values.laa_portal.idpSloTargetUrl | b64enc | quote }}
  laaPortalIdpCert: {{ .Values.laa_portal.idpCert | b64enc | quote }}
  laaPortalIdpCertFingerprintAlgorithm: {{ .Values.laa_portal.idpCertFingerprintAlgorithm | b64enc | quote }}
  laaPortalCertificate: {{ .Values.laa_portal.certificate | b64enc | quote }}
  laaPortalSecretKey: {{ .Values.laa_portal.secretKey | b64enc | quote }}
  laaPortalMockSaml: {{ .Values.laa_portal.mockSaml | b64enc | quote }}
  providerDetailsUrl: {{ .Values.provider_details.url | b64enc | quote }}
  trueLayerClientId: {{ .Values.trueLayer.clientId | b64enc | quote }}
  trueLayerClientSecret: {{ .Values.trueLayer.clientSecret | b64enc | quote }}
  trueLayerEnableMock: {{ .Values.trueLayer.enableMock | b64enc | quote }}
  secureDataSecret: {{ .Values.secureData.secret | b64enc | quote }}
  sidekiqWebUiPassword: {{ .Values.worker.webUiPassword | b64enc | quote }}
  adminAllowReset: {{ .Values.admin.allowReset | b64enc | quote }}
  adminAllowCreateTestApplications: {{ .Values.admin.allowCreateTestApplications | b64enc | quote }}
  {{if .Values.admin.allowAdminPassword }}
  adminPassword: {{ .Values.admin.password | b64enc | quote }}
  {{ end }}
  googleTagManagerTrackingId: {{ .Values.google_tag_manager.trackingId | b64enc | quote }}
  googleClientId: {{ .Values.google.clientId | b64enc | quote }}
  googleClientSecret: {{ .Values.google.clientSecret | b64enc | quote }}
  checkFinancialEligibilityHost: {{ .Values.checkFinancialEligibility.host | b64enc | quote }}
  legalFrameworkApiHost:  {{ .Values.legalFrameworkApi.host | b64enc | quote }}
  email_domainSuffix: {{ .Values.email_domain.suffix | b64enc | quote }}
  adminShowForm: {{ .Values.admin.showForm | b64enc | quote }}
  policyDisregardsStartDate: {{ .Values.policy_disregards_start_date | b64enc | quote }}
