apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apply-for-legal-aid.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  secretKey: {{ .Values.deploy.secretKey | b64enc | quote }}
  railsMasterKey: {{ .Values.deploy.rails_master_key | b64enc | quote }}
  {{if .Values.postgresql.enabled }}
  postgresqlDatabase: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  postgresqlUsername: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresqlPassword: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{ end }}
  sentryDsn: {{ .Values.sentry.dsn | b64enc | quote }}
  govukNotifyApiKey: {{ .Values.govuk_notify.api_key | b64enc | quote }}
  govukNotifyEnv: {{ .Values.govuk_notify.environment | b64enc | quote }}
  ordnanaceSurveyApiKey: {{ .Values.ordnanace_survey.api_key | b64enc | quote }}
  benefitCheckerLscServiceName: {{ .Values.benefit_checker.lscServiceName | b64enc | quote }}
  benefitCheckerClientOrgId: {{ .Values.benefit_checker.clientOrgId | b64enc | quote }}
  benefitCheckerClientUserId: {{ .Values.benefit_checker.clientUserId | b64enc | quote }}
  benefitCheckerWsdlUrl: {{ .Values.benefit_checker.wsdlUrl | b64enc | quote }}
  laaPortalIdpSsoTargetUrl: {{ .Values.laa_portal.idpSsoTargetUrl | b64enc | quote }}
  laaPortalIdpSloTargetUrl: {{ .Values.laa_portal.idpSloTargetUrl | b64enc | quote }}
  laaPortalIdpCert: {{ .Values.laa_portal.idpCert | b64enc | quote }}
  laaPortalIdpCertFingerprintAlgorithm: {{ .Values.laa_portal.idpCertFingerprintAlgorithm | b64enc | quote }}
  laaPortalCertificate: {{ .Values.laa_portal.certificate | b64enc | quote }}
  laaPortalSecretKey: {{ .Values.laa_portal.secretKey | b64enc | quote }}
  laaPortalMockSaml: {{ .Values.laa_portal.mockSaml | b64enc | quote }}
  providerDetailsUrl: {{ .Values.provider_details.url | b64enc | quote }}
  providerDetailsMock: {{ .Values.provider_details.mock | b64enc | quote }}
  trueLayerClientId: {{ .Values.trueLayer.clientId | b64enc | quote }}
  trueLayerClientSecret: {{ .Values.trueLayer.clientSecret | b64enc | quote }}
  trueLayerEnableMock: {{ .Values.trueLayer.enableMock | b64enc | quote }}
  secureDataSecret: {{ .Values.secureData.secret | b64enc | quote }}
  sidekiqWebUiPassword: {{ .Values.worker.webUiPassword | b64enc | quote }}
  adminAllowReset: {{ .Values.admin.allowReset | b64enc | quote }}
  adminAllowCreateTestApplications: {{ .Values.admin.allowCreateTestApplications | b64enc | quote }}
  adminAllowNonPassportedRoute: {{ .Values.admin.allowNonPassportedRoute | b64enc | quote }}
  adminPassword: {{ .Values.admin.password | b64enc | quote }}
  googleTagManagerTrackingId: {{ .Values.google_tag_manager.trackingId | b64enc | quote }}
  slackAlertsWebhook: {{ .Values.slack_alerts_webhook | b64enc | quote }}
