apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apply-for-legal-aid.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  {{if .Values.postgresql.enabled }}
  postgresqlDatabase: {{ .Values.postgresql.auth.database | b64enc | quote }}
  {{ end }}
  ordnanceSurveyApiKey: {{ .Values.ordnance_survey.api_key | b64enc | quote }}
  benefitCheckerLscServiceName: {{ .Values.benefit_checker.lscServiceName | b64enc | quote }}
  benefitCheckerWsdlUrl: {{ .Values.benefit_checker.wsdlUrl | b64enc | quote }}
  ccmsSoaSubmitApplications: {{ .Values.ccms_soa.submit_applications | b64enc | quote }}
  ccmsSoaClientPasswordType: {{ .Values.ccms_soa.clientPasswordType | b64enc | quote }}
  ccmsSoaUserRole: {{ .Values.ccms_soa.userRole | b64enc | quote }}
  ccmsSoaCaseServicesWsdl: {{ .Values.ccms_soa.caseServicesWsdl | b64enc | quote }}
  ccmsSoaClientProxyServiceWsdl: {{ .Values.ccms_soa.clientProxyServiceWsdl | b64enc | quote }}
  ccmsSoaDocumentServicesWsdl: {{ .Values.ccms_soa.documentServicesWsdl | b64enc | quote }}
  ccmsSoaGetReferenceDataWsdl: {{ .Values.ccms_soa.getReferenceDataWsdl | b64enc | quote }}
  geckoboardApiKey: {{ .Values.geckoboard.api_key | b64enc | quote }}
  laaPortalIdpSsoTargetUrl: {{ .Values.laa_portal.idpSsoTargetUrl | b64enc | quote }}
  laaPortalIdpSloTargetUrl: {{ .Values.laa_portal.idpSloTargetUrl | b64enc | quote }}
  laaPortalIdpCertFingerprintAlgorithm: {{ .Values.laa_portal.idpCertFingerprintAlgorithm | b64enc | quote }}
  laaPortalMockSaml: {{ .Values.laa_portal.mockSaml | b64enc | quote }}
  providerDetailsUrl: {{ .Values.provider_details.url | b64enc | quote }}
  pdaUrl: {{ .Values.pda.url | b64enc | quote }}
  trueLayerClientId: {{ .Values.trueLayer.clientId | b64enc | quote }}
  trueLayerClientSecret: {{ .Values.trueLayer.clientSecret | b64enc | quote }}
  trueLayerEnableMock: {{ .Values.trueLayer.enableMock | b64enc | quote }}
  adminAllowReset: {{ .Values.admin.allowReset | b64enc | quote }}
  adminAllowCreateTestApplications: {{ .Values.admin.allowCreateTestApplications | b64enc | quote }}
  googleTagManagerTrackingId: {{ .Values.google_tag_manager.trackingId | b64enc | quote }}
  checkFinancialEligibilityCivilHost: {{ .Values.checkFinancialEligibility.civil_host | b64enc | quote }}
  legalFrameworkApiHost:  {{ .Values.legalFrameworkApi.host | b64enc | quote }}
  legalFrameworkApiHostJS:  {{ .Values.legalFrameworkApi.js_host | b64enc | quote }}
  email_domainSuffix: {{ .Values.email_domain.suffix | b64enc | quote }}
  adminShowForm: {{ .Values.admin.showForm | b64enc | quote }}
  policyDisregardsStartDate: {{ .Values.policy_disregards_start_date | b64enc | quote }}
  hmrcApiHost: {{ .Values.hmrc_interface.host | b64enc | quote  }}
  hmrcApiUid: {{ .Values.hmrc_interface.uid | b64enc | quote  }}
  hmrcApiSecret: {{ .Values.hmrc_interface.secret | b64enc | quote  }}
  hmrcDurationCheck: {{ .Values.hmrc_interface.duration | b64enc | quote  }}
  hmrcUseDevMock: {{ .Values.hmrc_interface.hmrc_use_dev_mock | b64enc | quote  }}
  googleSheetsClientEmail: {{ .Values.googleSheets.clientEmail | b64enc | quote  }}
  googleSheetsClientId: {{ .Values.googleSheets.clientId | b64enc | quote  }}
  googleSheetsSpreadsheetId: {{ .Values.googleSheets.spreadsheetId | b64enc | quote  }}
  googleSheetsCFEComparisonSpreadsheetId: {{ .Values.googleSheets.cfe_comparison_sheet_id | b64enc | quote  }}
  googleDataStudioUrl: {{ .Values.google_data_studio_url | b64enc | quote  }}
  maintenanceMode: {{ .Values.maintenance_mode.enabled | b64enc | quote  }}
  collectHmrcData: {{ .Values.collect_hmrc_data.enabled | b64enc | quote  }}
