apiVersion: v1
kind: Service
metadata:
  name: {{ template "apply-for-legal-aid.fullname" . }}-clamav
  labels:
    service: {{ template "apply-for-legal-aid.fullname" . }}-clamav
    app: {{ template "apply-for-legal-aid.name" . }}
    chart: {{ template "apply-for-legal-aid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    service: {{ template "apply-for-legal-aid.fullname" . }}-clamav
  clusterIP: None
  ports:
    - name: zombie-port # Actually, we do not use this port but it is still needed to allow the service to receive TCP traffic.
      port: 1234
      targetPort: 1234
