---
http_interactions:
- request:
    method: get
    uri: https://api.os.uk/search/places/v1/postcode?key=&lr=EN&postcode=SW1H9EA
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v2.13.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Date:
      - Mon, 14 Jul 2025 11:55:55 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '90'
      Connection:
      - keep-alive
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"fault":{"faultstring":"Invalid ApiKey","detail":{"errorcode":"oauth.v2.InvalidApiKey"}}}'
  recorded_at: Mon, 14 Jul 2025 11:55:55 GMT
recorded_with: VCR 6.3.1
