---
http_interactions:
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments
    body:
      encoding: UTF-8
      string: '{"client_reference_id":"L-AMC-176","submission_date":"2021-08-02","matter_proceeding_type":"domestic_abuse"}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 02 Aug 2021 07:33:28 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"1a9feb126b7f882903097f6e47e326c8"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - a1fbe069333cd7f9984866c19d8d51b0
      X-Runtime:
      - '0.027327'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"assessment_id":"c13630aa-e18d-4b7e-8113-0775cd9a38a6","errors":[]}'
  recorded_at: Mon, 02 Aug 2021 07:33:28 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/c13630aa-e18d-4b7e-8113-0775cd9a38a6/applicant
    body:
      encoding: UTF-8
      string: '{"applicant":{"date_of_birth":"1983-04-02","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true}}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 02 Aug 2021 07:33:28 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - e90f020802d0f7d05847e69f168fa47b
      X-Runtime:
      - '0.010784'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Mon, 02 Aug 2021 07:33:28 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/c13630aa-e18d-4b7e-8113-0775cd9a38a6/capitals
    body:
      encoding: UTF-8
      string: '{"bank_accounts":[{"description":"Money not in a bank account","value":"4000.0"},{"description":"Online
        current accounts","value":0},{"description":"Online savings accounts","value":0}],"non_liquid_capital":[]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 02 Aug 2021 07:33:28 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 6c2e26672ce5b901132b2869a77688d4
      X-Runtime:
      - '0.017899'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Mon, 02 Aug 2021 07:33:28 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/c13630aa-e18d-4b7e-8113-0775cd9a38a6/vehicles
    body:
      encoding: UTF-8
      string: '{"vehicles":[]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 02 Aug 2021 07:33:28 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - acb52aef8b08211a62c00d8ff65c8930
      X-Runtime:
      - '0.004958'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Mon, 02 Aug 2021 07:33:28 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/c13630aa-e18d-4b7e-8113-0775cd9a38a6/properties
    body:
      encoding: UTF-8
      string: '{"properties":{"main_home":{"value":0.0,"outstanding_mortgage":0.0,"percentage_owned":0.0,"shared_with_housing_assoc":false},"additional_properties":[{"value":0,"outstanding_mortgage":0,"percentage_owned":0,"shared_with_housing_assoc":false}]}}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 02 Aug 2021 07:33:28 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 5f5c7b1059bb6f4d2479d4bb93d48839
      X-Runtime:
      - '0.019456'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Mon, 02 Aug 2021 07:33:28 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/c13630aa-e18d-4b7e-8113-0775cd9a38a6/explicit_remarks
    body:
      encoding: UTF-8
      string: '{"explicit_remarks":[{"category":"policy_disregards","details":[]}]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 02 Aug 2021 07:33:28 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 67cebc443590670d6d15f61fef0d3c3c
      X-Runtime:
      - '0.003506'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Mon, 02 Aug 2021 07:33:28 GMT
- request:
    method: get
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/c13630aa-e18d-4b7e-8113-0775cd9a38a6
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 02 Aug 2021 07:33:29 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"b9fa777af35bb4224d059977002af309"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - f866c1fd434bd41e5eb60d8e0bc03718
      X-Runtime:
      - '0.082115'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"version":"3","timestamp":"2021-08-02T07:33:29.168Z","success":true,"assessment":{"id":"c13630aa-e18d-4b7e-8113-0775cd9a38a6","client_reference_id":"L-AMC-176","submission_date":"2021-08-02","matter_proceeding_type":"domestic_abuse","assessment_result":"contribution_required","applicant":{"date_of_birth":"1983-04-02","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true,"self_employed":false},"gross_income":{"summary":{"total_gross_income":"0.0","upper_threshold":"999999999999.0","assessment_result":"pending"},"irregular_income":{"monthly_equivalents":{"student_loan":null}},"state_benefits":{"monthly_equivalents":{"all_sources":"0.0","cash_transactions":"0.0","bank_transactions":[]}},"other_income":{"monthly_equivalents":{"bank_transactions":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","pension":"0.0"},"cash_transactions":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","pension":"0.0"},"all_sources":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","pension":"0.0"}}}},"disposable_income":{"monthly_equivalents":{"bank_transactions":{"child_care":"0.0","rent_or_mortgage":"0.0","maintenance_out":"0.0","legal_aid":"0.0"},"cash_transactions":{"child_care":"0.0","rent_or_mortgage":"0.0","maintenance_out":"0.0","legal_aid":"0.0"},"all_sources":{"child_care":"0.0","rent_or_mortgage":"0.0","maintenance_out":"0.0","legal_aid":"0.0"}},"childcare_allowance":"0.0","deductions":{"dependants_allowance":"0.0","disregarded_state_benefits":0.0},"dependant_allowance":"0.0","maintenance_allowance":"0.0","gross_housing_costs":"0.0","housing_benefit":"0.0","net_housing_costs":"0.0","total_outgoings_and_allowances":"0.0","total_disposable_income":"0.0","lower_threshold":"315.0","upper_threshold":"999999999999.0","assessment_result":"pending","income_contribution":"0.0"},"capital":{"capital_items":{"liquid":[{"description":"Money
        not in a bank account","value":"4000.0"},{"description":"Online current accounts","value":"0.0"},{"description":"Online
        savings accounts","value":"0.0"}],"non_liquid":[],"vehicles":[],"properties":{"main_home":{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":true,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"100000.0","assessed_equity":"0.0"},"additional_properties":[{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":false,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"0.0","assessed_equity":"0.0"}]}},"total_liquid":"4000.0","total_non_liquid":"0.0","total_vehicle":"0.0","total_property":"0.0","total_mortgage_allowance":"999999999999.0","total_capital":"4000.0","pensioner_capital_disregard":"0.0","assessed_capital":"4000.0","lower_threshold":"3000.0","upper_threshold":"999999999999.0","assessment_result":"contribution_required","capital_contribution":"1000.0"},"remarks":{}}}'
  recorded_at: Mon, 02 Aug 2021 07:33:29 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk/merits_tasks
    body:
      encoding: UTF-8
      string: '{"request_id":"83fd8293-5d2d-4fe2-b7df-d5c71b7c6275","proceeding_types":["DA004"]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 02 Aug 2021 07:33:29 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept
      Etag:
      - W/"a5003b4f6ba0ac32570b5e71c7d3b8d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 5bd9a836d193c0c49e650af3e3d9fcb9
      X-Runtime:
      - '0.072119'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"request_id":"83fd8293-5d2d-4fe2-b7df-d5c71b7c6275","success":true,"application":{"tasks":{"latest_incident_details":[],"opponent_details":[],"statement_of_case":[]}},"proceeding_types":[{"ccms_code":"DA004","tasks":{"chances_of_success":[]}}]}'
  recorded_at: Mon, 02 Aug 2021 07:33:29 GMT
recorded_with: VCR 6.0.0
