---
http_interactions:
- request:
    method: post
    uri: https://check-financial-eligibility-staging.cloud-platform.service.justice.gov.uk/assessments
    body:
      encoding: UTF-8
      string: '{"client_reference_id":"L-6UV-XYF","submission_date":"2022-05-10","proceeding_types":{"ccms_codes":["DA001"]}}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=4
      User-Agent:
      - Faraday v1.10.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 May 2022 19:47:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"7e49b55b04b5d3b75e710b806cb44ad3"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 7124bd30aac598d7a107d3005a9ade7e
      X-Runtime:
      - '0.032177'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"assessment_id":"e7452e93-88ff-430f-bd32-05a70d67d095","errors":[]}'
  recorded_at: Tue, 10 May 2022 19:47:01 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.cloud-platform.service.justice.gov.uk/assessments/e7452e93-88ff-430f-bd32-05a70d67d095/applicant
    body:
      encoding: UTF-8
      string: '{"applicant":{"date_of_birth":"1995-04-17","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true}}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=4
      User-Agent:
      - Faraday v1.10.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 May 2022 19:47:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 0ec9ea6455a15cc3dc6d5d49df8d527f
      X-Runtime:
      - '0.027064'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Tue, 10 May 2022 19:47:01 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.cloud-platform.service.justice.gov.uk/assessments/e7452e93-88ff-430f-bd32-05a70d67d095/capitals
    body:
      encoding: UTF-8
      string: '{"bank_accounts":[],"non_liquid_capital":[]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=4
      User-Agent:
      - Faraday v1.10.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 May 2022 19:47:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 10954cec49dd8de95cf530153fb9469d
      X-Runtime:
      - '0.022219'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Tue, 10 May 2022 19:47:01 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.cloud-platform.service.justice.gov.uk/assessments/e7452e93-88ff-430f-bd32-05a70d67d095/vehicles
    body:
      encoding: UTF-8
      string: '{"vehicles":[]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=4
      User-Agent:
      - Faraday v1.10.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 May 2022 19:47:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 1181c1132b01d280c48431bed96b403e
      X-Runtime:
      - '0.022054'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Tue, 10 May 2022 19:47:01 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.cloud-platform.service.justice.gov.uk/assessments/e7452e93-88ff-430f-bd32-05a70d67d095/properties
    body:
      encoding: UTF-8
      string: '{"properties":{"main_home":{"value":0.0,"outstanding_mortgage":0.0,"percentage_owned":0.0,"shared_with_housing_assoc":false},"additional_properties":[{"value":0,"outstanding_mortgage":0,"percentage_owned":0,"shared_with_housing_assoc":false}]}}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=4
      User-Agent:
      - Faraday v1.10.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 May 2022 19:47:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 6323ecb3d87ba50cb8ce69a39ff57c76
      X-Runtime:
      - '0.025713'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Tue, 10 May 2022 19:47:01 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.cloud-platform.service.justice.gov.uk/assessments/e7452e93-88ff-430f-bd32-05a70d67d095/explicit_remarks
    body:
      encoding: UTF-8
      string: '{"explicit_remarks":[{"category":"policy_disregards","details":[]}]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=4
      User-Agent:
      - Faraday v1.10.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 May 2022 19:47:02 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - e708a5e0b0b012fc9dcc86b215b1989f
      X-Runtime:
      - '0.017686'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Tue, 10 May 2022 19:47:02 GMT
- request:
    method: get
    uri: https://check-financial-eligibility-staging.cloud-platform.service.justice.gov.uk/assessments/e7452e93-88ff-430f-bd32-05a70d67d095
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=4
      User-Agent:
      - Faraday v1.10.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 May 2022 19:47:02 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"0c937e16599a192eb99aff91de08cb04"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - c391ec5de227b025be4888170cee746b
      X-Runtime:
      - '0.091462'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"version":"4","timestamp":"2022-05-10T19:47:02.339Z","success":true,"result_summary":{"overall_result":{"result":"eligible","capital_contribution":0.0,"income_contribution":0.0,"matter_types":[{"matter_type":"domestic_abuse","result":"eligible"}],"proceeding_types":[{"ccms_code":"DA001","result":"eligible"}]},"gross_income":{"total_gross_income":0.0,"proceeding_types":[{"ccms_code":"DA001","upper_threshold":999999999999.0,"result":"pending"}]},"disposable_income":{"dependant_allowance":0.0,"gross_housing_costs":0.0,"housing_benefit":0.0,"net_housing_costs":0.0,"maintenance_allowance":0.0,"total_outgoings_and_allowances":0.0,"total_disposable_income":0.0,"employment_income":{"gross_income":0.0,"benefits_in_kind":0.0,"tax":0.0,"national_insurance":0.0,"fixed_employment_deduction":0.0,"net_employment_income":0.0},"income_contribution":0.0,"proceeding_types":[{"ccms_code":"DA001","upper_threshold":999999999999.0,"lower_threshold":315.0,"result":"pending"}]},"capital":{"total_liquid":0.0,"total_non_liquid":0.0,"total_vehicle":0.0,"total_property":0.0,"total_mortgage_allowance":999999999999.0,"total_capital":0.0,"pensioner_capital_disregard":0.0,"capital_contribution":0.0,"assessed_capital":0.0,"proceeding_types":[{"ccms_code":"DA001","lower_threshold":3000.0,"upper_threshold":999999999999.0,"result":"eligible"}]}},"assessment":{"id":"e7452e93-88ff-430f-bd32-05a70d67d095","client_reference_id":"L-6UV-XYF","submission_date":"2022-05-10","applicant":{"date_of_birth":"1995-04-17","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true,"self_employed":false},"gross_income":{"employment_income":[],"irregular_income":{"monthly_equivalents":{"student_loan":0.0}},"state_benefits":{"monthly_equivalents":{"all_sources":0.0,"cash_transactions":0.0,"bank_transactions":[]}},"other_income":{"monthly_equivalents":{"all_sources":{"friends_or_family":0.0,"maintenance_in":0.0,"property_or_lodger":0.0,"pension":0.0},"bank_transactions":{"friends_or_family":0.0,"maintenance_in":0.0,"property_or_lodger":0.0,"pension":0.0},"cash_transactions":{"friends_or_family":0.0,"maintenance_in":0.0,"property_or_lodger":0.0,"pension":0.0}}}},"disposable_income":{"monthly_equivalents":{"all_sources":{"child_care":0.0,"rent_or_mortgage":0.0,"maintenance_out":0.0,"legal_aid":0.0},"bank_transactions":{"child_care":0.0,"rent_or_mortgage":0.0,"maintenance_out":0.0,"legal_aid":0.0},"cash_transactions":{"child_care":0.0,"rent_or_mortgage":0.0,"maintenance_out":0.0,"legal_aid":0.0}},"childcare_allowance":0.0,"deductions":{"dependants_allowance":0.0,"disregarded_state_benefits":0.0}},"capital":{"capital_items":{"liquid":[],"non_liquid":[],"vehicles":[],"properties":{"main_home":{"value":0.0,"outstanding_mortgage":0.0,"percentage_owned":0.0,"main_home":true,"shared_with_housing_assoc":false,"transaction_allowance":0.0,"allowable_outstanding_mortgage":0.0,"net_value":0.0,"net_equity":0.0,"main_home_equity_disregard":100000.0,"assessed_equity":0.0},"additional_properties":[{"value":0.0,"outstanding_mortgage":0.0,"percentage_owned":0.0,"main_home":false,"shared_with_housing_assoc":false,"transaction_allowance":0.0,"allowable_outstanding_mortgage":0.0,"net_value":0.0,"net_equity":0.0,"main_home_equity_disregard":0.0,"assessed_equity":0.0}]}}},"remarks":{}}}'
  recorded_at: Tue, 10 May 2022 19:47:02 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/merits_tasks
    body:
      encoding: UTF-8
      string: '{"request_id":"10b37d2e-53bd-4e42-beed-995d4445ef3c","proceeding_types":["DA001"]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 May 2022 19:47:02 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"513a6fda9b5e256994ba55fafbb510a6"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - a241b43882d9fd2b14b965502bfc8285
      X-Runtime:
      - '0.030731'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"request_id":"10b37d2e-53bd-4e42-beed-995d4445ef3c","success":true,"application":{"tasks":{"latest_incident_details":[],"opponent_details":[],"statement_of_case":[]}},"proceeding_types":[{"ccms_code":"DA001","tasks":{"chances_of_success":[]}}]}'
  recorded_at: Tue, 10 May 2022 19:47:02 GMT
recorded_with: VCR 6.1.0
