---
http_interactions:
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments
    body:
      encoding: UTF-8
      string: '{"client_reference_id":"L-D5A-J6E","submission_date":"2021-09-29","matter_proceeding_type":"domestic_abuse"}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.8.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 29 Sep 2021 09:45:54 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"9d1e17eac71ddd9d1dbefc2d0f43b89d"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - ac69e3f9d05e3e4ba7d0e2ed31341737
      X-Runtime:
      - '0.067455'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"assessment_id":"bd08d858-5026-48bd-a8d0-91d0e2a892a3","errors":[]}'
  recorded_at: Wed, 29 Sep 2021 09:45:54 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/bd08d858-5026-48bd-a8d0-91d0e2a892a3/applicant
    body:
      encoding: UTF-8
      string: '{"applicant":{"date_of_birth":"1971-05-14","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true}}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.8.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 29 Sep 2021 09:45:54 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - deccbeea94dd6f95bcfd2a7b511a4fcd
      X-Runtime:
      - '0.035599'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Wed, 29 Sep 2021 09:45:54 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/bd08d858-5026-48bd-a8d0-91d0e2a892a3/capitals
    body:
      encoding: UTF-8
      string: '{"bank_accounts":[{"description":"Money not in a bank account","value":"4000.0"},{"description":"Online
        current accounts","value":0},{"description":"Online savings accounts","value":0}],"non_liquid_capital":[]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.8.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 29 Sep 2021 09:45:54 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 19a9fda27c4fce699951b7156718f808
      X-Runtime:
      - '0.023158'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Wed, 29 Sep 2021 09:45:54 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/bd08d858-5026-48bd-a8d0-91d0e2a892a3/vehicles
    body:
      encoding: UTF-8
      string: '{"vehicles":[]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.8.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 29 Sep 2021 09:45:54 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 86da9c7d44ece9f48d59b33c6301f452
      X-Runtime:
      - '0.006824'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Wed, 29 Sep 2021 09:45:54 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/bd08d858-5026-48bd-a8d0-91d0e2a892a3/properties
    body:
      encoding: UTF-8
      string: '{"properties":{"main_home":{"value":0.0,"outstanding_mortgage":0.0,"percentage_owned":0.0,"shared_with_housing_assoc":false},"additional_properties":[{"value":0,"outstanding_mortgage":0,"percentage_owned":0,"shared_with_housing_assoc":false}]}}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.8.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 29 Sep 2021 09:45:55 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 8d4e0c3387dc6eb24251be738828aec2
      X-Runtime:
      - '0.066772'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Wed, 29 Sep 2021 09:45:55 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/bd08d858-5026-48bd-a8d0-91d0e2a892a3/explicit_remarks
    body:
      encoding: UTF-8
      string: '{"explicit_remarks":[{"category":"policy_disregards","details":[]}]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.8.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 29 Sep 2021 09:45:55 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 0dca69296709737b99ccc0aa0624d7bd
      X-Runtime:
      - '0.002984'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Wed, 29 Sep 2021 09:45:55 GMT
- request:
    method: get
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/bd08d858-5026-48bd-a8d0-91d0e2a892a3
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.8.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 29 Sep 2021 09:45:55 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"1f0fa60d6efe03c4fde7a981dd097555"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 4c4105cecd7d5b265eabbd97e7c19ba2
      X-Runtime:
      - '0.075528'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"version":"3","timestamp":"2021-09-29T09:45:55.455Z","success":true,"assessment":{"id":"bd08d858-5026-48bd-a8d0-91d0e2a892a3","client_reference_id":"L-D5A-J6E","submission_date":"2021-09-29","matter_proceeding_type":"domestic_abuse","assessment_result":"contribution_required","applicant":{"date_of_birth":"1971-05-14","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true,"self_employed":false},"gross_income":{"summary":{"total_gross_income":"0.0","upper_threshold":"999999999999.0","assessment_result":"pending"},"irregular_income":{"monthly_equivalents":{"student_loan":null}},"state_benefits":{"monthly_equivalents":{"all_sources":"0.0","cash_transactions":"0.0","bank_transactions":[]}},"other_income":{"monthly_equivalents":{"bank_transactions":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","pension":"0.0"},"cash_transactions":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","pension":"0.0"},"all_sources":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","pension":"0.0"}}}},"disposable_income":{"monthly_equivalents":{"bank_transactions":{"child_care":"0.0","rent_or_mortgage":"0.0","maintenance_out":"0.0","legal_aid":"0.0"},"cash_transactions":{"child_care":"0.0","rent_or_mortgage":"0.0","maintenance_out":"0.0","legal_aid":"0.0"},"all_sources":{"child_care":"0.0","rent_or_mortgage":"0.0","maintenance_out":"0.0","legal_aid":"0.0"}},"childcare_allowance":"0.0","deductions":{"dependants_allowance":"0.0","disregarded_state_benefits":0.0},"dependant_allowance":"0.0","maintenance_allowance":"0.0","gross_housing_costs":"0.0","housing_benefit":"0.0","net_housing_costs":"0.0","total_outgoings_and_allowances":"0.0","total_disposable_income":"0.0","lower_threshold":"315.0","upper_threshold":"999999999999.0","assessment_result":"pending","income_contribution":"0.0"},"capital":{"capital_items":{"liquid":[{"description":"Money
        not in a bank account","value":"4000.0"},{"description":"Online current accounts","value":"0.0"},{"description":"Online
        savings accounts","value":"0.0"}],"non_liquid":[],"vehicles":[],"properties":{"main_home":{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":true,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"100000.0","assessed_equity":"0.0"},"additional_properties":[{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":false,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"0.0","assessed_equity":"0.0"}]}},"total_liquid":"4000.0","total_non_liquid":"0.0","total_vehicle":"0.0","total_property":"0.0","total_mortgage_allowance":"999999999999.0","total_capital":"4000.0","pensioner_capital_disregard":"0.0","assessed_capital":"4000.0","lower_threshold":"3000.0","upper_threshold":"999999999999.0","assessment_result":"contribution_required","capital_contribution":"1000.0"},"remarks":{}}}'
  recorded_at: Wed, 29 Sep 2021 09:45:55 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk/merits_tasks
    body:
      encoding: UTF-8
      string: '{"request_id":"5c19b3ca-c9a5-4875-ab72-647cf31fbf11","proceeding_types":["DA001"]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.8.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 29 Sep 2021 09:45:56 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept
      Etag:
      - W/"3abfb171af1c33019e9a8c416c5c5c73"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 99fb8174a82d77cc4dfa0b1e363c00ce
      X-Runtime:
      - '0.079113'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"request_id":"5c19b3ca-c9a5-4875-ab72-647cf31fbf11","success":true,"application":{"tasks":{"latest_incident_details":[],"opponent_details":[],"statement_of_case":[]}},"proceeding_types":[{"ccms_code":"DA001","tasks":{"chances_of_success":[]}}]}'
  recorded_at: Wed, 29 Sep 2021 09:45:56 GMT
recorded_with: VCR 6.0.0
