---
http_interactions:
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments
    body:
      encoding: UTF-8
      string: '{"client_reference_id":"L-BXH-LJ4","submission_date":"2021-07-30","matter_proceeding_type":"domestic_abuse"}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Jul 2021 12:28:33 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"cd165dad407b29ec04ebb13138b38f84"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 4042189c934339dfc89cc043dc50c4e8
      X-Runtime:
      - '0.028164'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"assessment_id":"8efa3266-8c7a-4e81-8e2b-6af6b3e81616","errors":[]}'
  recorded_at: Fri, 30 Jul 2021 12:28:33 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/8efa3266-8c7a-4e81-8e2b-6af6b3e81616/applicant
    body:
      encoding: UTF-8
      string: '{"applicant":{"date_of_birth":"1966-05-10","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true}}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Jul 2021 12:28:33 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - da006e80f42161ad0e998e2991c75ee7
      X-Runtime:
      - '0.012833'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 30 Jul 2021 12:28:34 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/8efa3266-8c7a-4e81-8e2b-6af6b3e81616/capitals
    body:
      encoding: UTF-8
      string: '{"bank_accounts":[{"description":"Money not in a bank account","value":"4000.0"},{"description":"Online
        current accounts","value":0},{"description":"Online savings accounts","value":0}],"non_liquid_capital":[]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Jul 2021 12:28:34 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 42529f99a7500155ae7784335df36497
      X-Runtime:
      - '0.029692'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 30 Jul 2021 12:28:34 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/8efa3266-8c7a-4e81-8e2b-6af6b3e81616/vehicles
    body:
      encoding: UTF-8
      string: '{"vehicles":[]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Jul 2021 12:28:34 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - c1f80a8fc8641ac0d94e7782c847fba8
      X-Runtime:
      - '0.005791'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 30 Jul 2021 12:28:35 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/8efa3266-8c7a-4e81-8e2b-6af6b3e81616/properties
    body:
      encoding: UTF-8
      string: '{"properties":{"main_home":{"value":0.0,"outstanding_mortgage":0.0,"percentage_owned":0.0,"shared_with_housing_assoc":false},"additional_properties":[{"value":0,"outstanding_mortgage":0,"percentage_owned":0,"shared_with_housing_assoc":false}]}}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Jul 2021 12:28:35 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - c97c7522e697c111b18595247af9b406
      X-Runtime:
      - '0.021189'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 30 Jul 2021 12:28:35 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/8efa3266-8c7a-4e81-8e2b-6af6b3e81616/explicit_remarks
    body:
      encoding: UTF-8
      string: '{"explicit_remarks":[{"category":"policy_disregards","details":[]}]}'
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Jul 2021 12:28:35 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"e156c1de751f0fc41f3ce5edefd256d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - bb50322ab9aa64efca05e9151ec96eac
      X-Runtime:
      - '0.003076'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"success":true,"errors":[]}'
  recorded_at: Fri, 30 Jul 2021 12:28:35 GMT
- request:
    method: get
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/8efa3266-8c7a-4e81-8e2b-6af6b3e81616
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=3
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Jul 2021 12:28:35 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept
      Etag:
      - W/"7948f50fdc3ec0a2c18d2e136aab5015"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 3481c8e6f1651f5f7aec76ddaba31c22
      X-Runtime:
      - '0.069404'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - sameorigin
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Content-Security-Policy:
      - default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'
        'unsafe-inline'
    body:
      encoding: UTF-8
      string: '{"version":"3","timestamp":"2021-07-30T12:28:35.757Z","success":true,"assessment":{"id":"8efa3266-8c7a-4e81-8e2b-6af6b3e81616","client_reference_id":"L-BXH-LJ4","submission_date":"2021-07-30","matter_proceeding_type":"domestic_abuse","assessment_result":"contribution_required","applicant":{"date_of_birth":"1966-05-10","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":true,"self_employed":false},"gross_income":{"summary":{"total_gross_income":"0.0","upper_threshold":"999999999999.0","assessment_result":"pending"},"irregular_income":{"monthly_equivalents":{"student_loan":null}},"state_benefits":{"monthly_equivalents":{"all_sources":"0.0","cash_transactions":"0.0","bank_transactions":[]}},"other_income":{"monthly_equivalents":{"bank_transactions":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","pension":"0.0"},"cash_transactions":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","pension":"0.0"},"all_sources":{"friends_or_family":"0.0","maintenance_in":"0.0","property_or_lodger":"0.0","pension":"0.0"}}}},"disposable_income":{"monthly_equivalents":{"bank_transactions":{"child_care":"0.0","rent_or_mortgage":"0.0","maintenance_out":"0.0","legal_aid":"0.0"},"cash_transactions":{"child_care":"0.0","rent_or_mortgage":"0.0","maintenance_out":"0.0","legal_aid":"0.0"},"all_sources":{"child_care":"0.0","rent_or_mortgage":"0.0","maintenance_out":"0.0","legal_aid":"0.0"}},"childcare_allowance":"0.0","deductions":{"dependants_allowance":"0.0","disregarded_state_benefits":0.0},"dependant_allowance":"0.0","maintenance_allowance":"0.0","gross_housing_costs":"0.0","housing_benefit":"0.0","net_housing_costs":"0.0","total_outgoings_and_allowances":"0.0","total_disposable_income":"0.0","lower_threshold":"315.0","upper_threshold":"999999999999.0","assessment_result":"pending","income_contribution":"0.0"},"capital":{"capital_items":{"liquid":[{"description":"Money
        not in a bank account","value":"4000.0"},{"description":"Online current accounts","value":"0.0"},{"description":"Online
        savings accounts","value":"0.0"}],"non_liquid":[],"vehicles":[],"properties":{"main_home":{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":true,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"100000.0","assessed_equity":"0.0"},"additional_properties":[{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":false,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"0.0","assessed_equity":"0.0"}]}},"total_liquid":"4000.0","total_non_liquid":"0.0","total_vehicle":"0.0","total_property":"0.0","total_mortgage_allowance":"999999999999.0","total_capital":"4000.0","pensioner_capital_disregard":"0.0","assessed_capital":"4000.0","lower_threshold":"3000.0","upper_threshold":"999999999999.0","assessment_result":"contribution_required","capital_contribution":"1000.0"},"remarks":{}}}'
  recorded_at: Fri, 30 Jul 2021 12:28:35 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk/merits_tasks
    body:
      encoding: UTF-8
      string: '{"request_id":"04bcca63-1c8b-4a24-81ee-cd9afd37db36","proceeding_types":["DA001"]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.5.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Jul 2021 12:28:36 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept
      Etag:
      - W/"946083c51f45ca8176f9f5b3d00351c3"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 66bc1bcc164754d20881183cd8a9dcce
      X-Runtime:
      - '0.048544'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"request_id":"04bcca63-1c8b-4a24-81ee-cd9afd37db36","success":true,"application":{"tasks":{"latest_incident_details":[],"opponent_details":[],"statement_of_case":[]}},"proceeding_types":[{"ccms_code":"DA001","tasks":{"chances_of_success":[]}}]}'
  recorded_at: Fri, 30 Jul 2021 12:28:36 GMT
recorded_with: VCR 6.0.0
