---

# differences from base.yml only applied
global_means:
  MEANS_REQD:
    generate_block?: true
    value: false
    br100_meaning: means required
    response_type: boolean
    user_defined: false
  IS_PASSPORTED:
    generate_block?: false
  BEN_DOB:
    generate_block?: false
  BEN_NI_NO:
    generate_block?: false
  BEN_SURNAME:
    generate_block?: false
  BEN_AWARD_DATE:
    generate_block?: false
  GB_INPUT_B_14WP2_8A:
    generate_block?: false
  GB_INPUT_B_3WP2_1A:
    generate_block?: false
  GB_INPUT_B_14WP2_7A:
    generate_block?: false
  GB_INPUT_B_8WP2_1A:
    generate_block?: false
  GB_INPUT_B_16WP2_7A:
    generate_block?: false
  GB_INPUT_B_5WP1_18A:
    generate_block?: false
  CLIENT_ELIGIBILITY:
    generate_block?: false
  PUI_CLIENT_ELIGIBILITY:
    generate_block?: false
  GB_INPUT_B_7WP2_1A:
    generate_block?: false
  GB_INPUT_B_4WP2_1A:
    generate_block?: false
  GB_INPUT_B_6WP2_1A:
    generate_block?: false
  GB_INPUT_B_5WP2_1A:
    generate_block?: false
  GB_INPUT_B_2WP2_1A:
    generate_block?: false
  GB_INPUT_B_9WP2_1A:
    generate_block?: false
  GB_INPUT_B_10WP2_1A:
    generate_block?: false
  GB_INPUT_B_1WP2_36A:
    generate_block?: false
  GB_INPUT_B_13WP2_7A:
    generate_block?: false
  GB_INPUT_B_15WP2_8A:
    generate_block?: false
  GB_INPUT_B_6WP3_240A:
    generate_block?: false
  GB_INPUT_B_1WP3_165A:
    generate_block?: false
  GB_INPUT_B_11WP2_3A:
    generate_block?: false
  GB_INPUT_B_12WP2_2A:
    generate_block?: false
  GB_INPUT_D_18WP2_1A:
    generate_block?: false
  GB_RFLAG_B_2WP3_01A:
    generate_block?: false
  DATE_ASSESSMENT_STARTED:
    generate_block?: false
  GB_INFER_B_1WP1_1A:
    value: true
    br100_meaning: The application is non means tested
    response_type: boolean
    user_defined: false
  MEANS_TASK_AUTO_GEN:
    generate_block?: false
  PASSPORTED_NINO:
    generate_block?: false
  SA_SCREEN9_4WP1_CHILDUNDER16NA:
    generate_block?: true
    value: true
    br100_meaning: 'Child: The client appears eligible'
    response_type: boolean
    user_defined: false

global_merits:
  GB_INFER_T_6WP1_66A:
    generate_block?: false
  COPY_SEPARATE_STATEMENT:
    generate_block?: false
  URGENT_HEARING_DATE:
    generate_block?: false
  DATE_ASSESSMENT_STARTED:
    generate_block?: false
  DATE_CLIENT_VISITED_FIRM:
    generate_block?: false

