---
http_interactions:
- request:
    method: get
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/proceeding_types/PB007
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v2.13.1
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 10 Jun 2025 11:38:50 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '1036'
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"56c5b7b6ad5fb4847b57750494444570"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 12df85f7469ba771dd2229fcc346f96b
      X-Runtime:
      - '0.011227'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"success":true,"ccms_code":"PB007","meaning":"Contact with a child
        in care","ccms_category_law_code":"MAT","ccms_matter_code":"KPBLW","name":"contact_child_in_care_sca","description":"to
        be represented on an application for contact with a child in care.","sca_core":false,"sca_related":true,"ccms_category_law":"Family","ccms_matter":"special
        children act (SCA)","cost_limitations":{"substantive":{"start_date":"1970-01-01","value":"25000.0"},"delegated_functions":{"start_date":"2021-09-13","value":"2250.0"}},"default_scope_limitations":{"substantive":{"code":"FM062","meaning":"Final
        hearing","description":"Limited to all steps up to and including final hearing
        and any action necessary to implement (but not enforce) the order."},"delegated_functions":{"code":"FM062","meaning":"Final
        hearing","description":"Limited to all steps up to and including final hearing
        and any action necessary to implement (but not enforce) the order."}},"service_levels":[{"level":3,"name":"Full
        Representation","stage":8,"proceeding_default":true}]}'
  recorded_at: Tue, 10 Jun 2025 11:38:50 GMT
recorded_with: VCR 6.3.1
