---
http_interactions:
- request:
    method: get
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/client_involvement_types
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 25 Aug 2022 10:41:55 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"8bf337339345d42d16a9e6062fb65ccf"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 8b31a741509b50a87a1c685f07cdc6ec
      X-Runtime:
      - '0.005322'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '[{"ccms_code":"A","description":"Applicant/claimant/petitioner"},{"ccms_code":"D","description":"Defendant/respondent"},{"ccms_code":"W","description":"Subject
        of proceedings (child)"},{"ccms_code":"I","description":"Intervenor"},{"ccms_code":"Z","description":"Joined
        party"}]'
  recorded_at: Thu, 25 Aug 2022 10:41:55 GMT
- request:
    method: get
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/client_involvement_types
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 25 Aug 2022 10:41:56 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"8bf337339345d42d16a9e6062fb65ccf"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 4ccaa3c384f81bbc281a50062a289686
      X-Runtime:
      - '0.004937'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '[{"ccms_code":"A","description":"Applicant/claimant/petitioner"},{"ccms_code":"D","description":"Defendant/respondent"},{"ccms_code":"W","description":"Subject
        of proceedings (child)"},{"ccms_code":"I","description":"Intervenor"},{"ccms_code":"Z","description":"Joined
        party"}]'
  recorded_at: Thu, 25 Aug 2022 10:41:56 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/proceeding_type_defaults
    body:
      encoding: UTF-8
      string: '{"proceeding_type_ccms_code":"DA001","delegated_functions_used":true,"client_involvement_type":"A"}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 25 Aug 2022 10:41:56 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"394350725076183ab4ae0116449123c3"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - b73f49f9a559ef3d9c6a0e26c3a6bbf4
      X-Runtime:
      - '0.013575'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"success":true,"requested_params":{"proceeding_type_ccms_code":"DA001","delegated_functions_used":true,"client_involvement_type":"A"},"default_level_of_service":{"level":3,"name":"Full
        Representation","stage":8},"default_scope":{"code":"CV117","meaning":"Interim
        order inc. return date","description":"Limited to all steps necessary to apply
        for an interim order; where application is made without notice to include
        representation on the return date.","additional_params":[]}}'
  recorded_at: Thu, 25 Aug 2022 10:41:56 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/proceeding_type_defaults
    body:
      encoding: UTF-8
      string: '{"proceeding_type_ccms_code":"DA001","delegated_functions_used":true,"client_involvement_type":"A"}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 25 Aug 2022 10:41:57 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"394350725076183ab4ae0116449123c3"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 2ecd0a9f3f3db4f999ed43ead204aede
      X-Runtime:
      - '0.015227'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"success":true,"requested_params":{"proceeding_type_ccms_code":"DA001","delegated_functions_used":true,"client_involvement_type":"A"},"default_level_of_service":{"level":3,"name":"Full
        Representation","stage":8},"default_scope":{"code":"CV117","meaning":"Interim
        order inc. return date","description":"Limited to all steps necessary to apply
        for an interim order; where application is made without notice to include
        representation on the return date.","additional_params":[]}}'
  recorded_at: Thu, 25 Aug 2022 10:41:57 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/proceeding_type_defaults
    body:
      encoding: UTF-8
      string: '{"proceeding_type_ccms_code":"DA001","delegated_functions_used":true,"client_involvement_type":"A"}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 25 Aug 2022 10:41:57 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"394350725076183ab4ae0116449123c3"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - bc4b0c0981b3b29682256dbb6bad7dbe
      X-Runtime:
      - '0.010417'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"success":true,"requested_params":{"proceeding_type_ccms_code":"DA001","delegated_functions_used":true,"client_involvement_type":"A"},"default_level_of_service":{"level":3,"name":"Full
        Representation","stage":8},"default_scope":{"code":"CV117","meaning":"Interim
        order inc. return date","description":"Limited to all steps necessary to apply
        for an interim order; where application is made without notice to include
        representation on the return date.","additional_params":[]}}'
  recorded_at: Thu, 25 Aug 2022 10:41:57 GMT
- request:
    method: post
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/proceeding_type_defaults
    body:
      encoding: UTF-8
      string: '{"proceeding_type_ccms_code":"DA001","delegated_functions_used":true,"client_involvement_type":"A"}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.10.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 25 Aug 2022 10:41:58 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"394350725076183ab4ae0116449123c3"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 3dd8c36d8029d0fe75faaa6b1de2aa35
      X-Runtime:
      - '0.015473'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"success":true,"requested_params":{"proceeding_type_ccms_code":"DA001","delegated_functions_used":true,"client_involvement_type":"A"},"default_level_of_service":{"level":3,"name":"Full
        Representation","stage":8},"default_scope":{"code":"CV117","meaning":"Interim
        order inc. return date","description":"Limited to all steps necessary to apply
        for an interim order; where application is made without notice to include
        representation on the return date.","additional_params":[]}}'
  recorded_at: Thu, 25 Aug 2022 10:41:58 GMT
recorded_with: VCR 6.1.0
