###################
# provider offices
###################
def stub_provider_offices
  stub_request(:get, %r{#{Rails.configuration.x.pda.url}/provider-users/test-user/provider-offices})
    .to_return(
      status: 200,
      body: provider_offices_json,
      headers: { "Content-Type" => "application/json; charset=utf-8" },
    )
end

def provider_offices_json
  {
    firm: {
      ccmsFirmId: 99_999,
      firmId: 1639,
      firmName: "Test firm",
      firmNumber: "1639",
    },
    officeCodes: [
      {
        ccmsFirmOfficeId: 111_111,
        firmOfficeCode: "1A111B",
      },
    ],
    user: {
      ccmsContactId: 494_000,
    },
  }.to_json
end

def stub_other_provider_offices
  stub_request(:get, %r{#{Rails.configuration.x.pda.url}/provider-users/other-user/provider-offices})
    .to_return(
      status: 200,
      body: other_provider_offices_json,
      headers: { "Content-Type" => "application/json; charset=utf-8" },
    )
end

def other_provider_offices_json
  {
    firm: {
      ccmsFirmId: 99_999,
      firmId: 1639,
      firmName: "Test firm",
      firmNumber: "1639",
    },
    officeCodes: [
      {
        ccmsFirmOfficeId: 222_222,
        firmOfficeCode: "2A222B",
      },
    ],
    user: {
      ccmsContactId: 494_000,
    },
  }.to_json
end

#################
# firm offices
#################
def stub_provider_firm_offices
  stub_request(:get, %r{#{Rails.configuration.x.pda.url}/provider-firms/1639/provider-offices})
  .to_return(
    status: 200,
    body: provider_firm_offices_json,
    headers: { "Content-Type" => "application/json; charset=utf-8" },
  )
end

def provider_firm_offices_json
  {
    firm: {
      ccmsFirmId: 99_999,
      firmId: 1639,
      firmName: "Test firm",
      firmNumber: "1639",
    },
    offices: [
      {
        ccmsFirmOfficeId: 111_111,
        firmOfficeCode: "1A111B",
      },
      {
        ccmsFirmOfficeId: 222_222,
        firmOfficeCode: "2A222B",
      },
    ],
  }.to_json
end

###################
# office schedules
###################
def stub_office_schedules_not_found_for(office_code)
  stub_request(:get, %r{#{Rails.configuration.x.pda.url}/provider-offices/#{office_code}/schedules})
    .to_return(
      status: 204,
      body: nil,
      headers: { "Content-Type" => "application/json; charset=utf-8" },
    )
end

def stub_office_schedules_for_0x395u
  stub_request(:get, %r{#{Rails.configuration.x.pda.url}/provider-offices/0X395U/schedules})
    .to_return(
      status: 200,
      body: office_schedules_json,
      headers: { "Content-Type" => "application/json; charset=utf-8" },
    )
end

def stub_provider_user_for_test_provider
  stub_request(:get, %r{#{Rails.configuration.x.pda.url}/provider-users/test_provider})
    .to_return(
      status: 200,
      body: provider_user_json,
      headers: { "Content-Type" => "application/json; charset=utf-8" },
    )
end

# Taken from:
#  https://laa-provider-details-api-preprod.apps.live.cloud-platform.service.justice.gov.uk/provider-offices/0X395U/schedules
#
# TODO: trim down to only what we need, when we know what we need :)
#
def office_schedules_json
  {
    firm: {
      firmNumber: "1639",
      firmId: 1639,
      ccmsFirmId: 19_148,
      parentFirmId: 0,
      firmName: "DAVID GRAY LLP",
      firmType: "Legal Services Provider",
      constitutionalStatus: "LLP",
      solicitorAdvocateYN: nil,
      advocateLevel: nil,
      barCouncilRoll: nil,
      companyHouseNumber: nil,
    },
    office: {
      firmOfficeId: 4545,
      ccmsFirmOfficeId: 137_570,
      firmOfficeCode: "0X395U",
      officeName: "0X395U,OLD COUNTY COURT",
      officeCodeAlt: "DAVID GRAY LLP",
      type: "Legal Services Supplier (Civil/Crime/Both/Mediator)",
    },
    pds: false,
    schedules: [
      {
        contractType: "Standard",
        contractDescription: "2024 Standard Civil Contract",
        contractNumber: "1255422",
        contractReference: "01/0X395U/2024/1",
        contractStatus: "Open",
        contractAuthorizationStatus: "APPROVED",
        contractStartDate: "2024-09-01",
        contractEndDate: "2026-06-30",
        areaOfLaw: "LEGAL HELP",
        scheduleType: "Standard",
        scheduleNumber: "0X395U/2024/01",
        scheduleContractNumber: "1255422",
        scheduleContractReference: "01/0X395U/2024/1",
        scheduleAuthorizationStatus: "APPROVED",
        scheduleStatus: "Open",
        scheduleStartDate: "2024-09-01",
        scheduleEndDate: "2025-08-31",
        scheduleLines: [
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "AAP",
            description: "Legal Help (Civil).Claims Against Public Authorities",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "COM",
            description: "Legal Help (Civil).Community Care",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "CON",
            description: "Legal Help (Civil).Consumer General Contract",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "DEB",
            description: "Legal Help (Civil).Debt",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "DISC",
            description: "Legal Help (Civil).Discrimination",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "EDU",
            description: "Legal Help (Civil).Education",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "EMP",
            description: "Legal Help (Civil).Employment",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "HOU",
            description: "Legal Help (Civil).Housing",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "IMMAS",
            description: "Legal Help (Civil).Immigration - Asylum",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "IMMOT",
            description: "Legal Help (Civil).Immigration",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "MAT",
            description: "Legal Help (Civil).Family",
            devolvedPowersStatus: "Yes - Excluding JR Proceedings",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "N/A",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "1",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "MED",
            description: "Legal Help (Civil).Clinical Negligence",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "MHE",
            description: "Legal Help (Civil).Mental Health",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "MSC",
            description: "Legal Help (Civil).Residual(Miscellaneous)",
            devolvedPowersStatus: "Yes - Excluding JR Proceedings",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "N/A",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "1",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "PI",
            description: "Legal Help (Civil).Personal Injury",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "PUB",
            description: "Legal Help (Civil).Public Law",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "WB",
            description: "Legal Help (Civil).Welfare Benefits",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "LEGAL HELP",
            categoryOfLaw: "ELA",
            description: "Legal Help (Civil).Early Legal Advice",
            devolvedPowersStatus: "No",
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: "No",
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: "0",
            maximumToleranceCount: "0",
            minimumLicenseCount: "0",
            maximumLicenseCount: "0",
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
        ],
        nmsAuths: [],
      },
      {
        contractType: "Standard",
        contractDescription: "2022 Standard Crime Contract",
        contractNumber: "1164771",
        contractReference: "CRM/08/0X395U/22",
        contractStatus: "Open",
        contractAuthorizationStatus: "APPROVED",
        contractStartDate: "2022-10-01",
        contractEndDate: "2025-09-30",
        areaOfLaw: "CRIME LOWER",
        scheduleType: "Standard",
        scheduleNumber: "CRM/0X395U/23",
        scheduleContractNumber: "1164771",
        scheduleContractReference: "CRM/08/0X395U/22",
        scheduleAuthorizationStatus: "APPROVED",
        scheduleStatus: "Open",
        scheduleStartDate: "2023-10-01",
        scheduleEndDate: "2025-09-30",
        scheduleLines: [
          {
            areaOfLaw: "CRIME LOWER",
            categoryOfLaw: "INVEST",
            description: "Crime Lower.Criminal Investigations and Criminal Proceedings",
            devolvedPowersStatus: nil,
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: nil,
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "1",
            minimumToleranceCount: nil,
            maximumToleranceCount: nil,
            minimumLicenseCount: nil,
            maximumLicenseCount: nil,
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "CRIME LOWER",
            categoryOfLaw: "APPEALS",
            description: "Crime Lower.Appeals and Reviews",
            devolvedPowersStatus: nil,
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: nil,
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "1",
            minimumToleranceCount: nil,
            maximumToleranceCount: nil,
            minimumLicenseCount: nil,
            maximumLicenseCount: nil,
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
          {
            areaOfLaw: "CRIME LOWER",
            categoryOfLaw: "PRISON",
            description: "Crime Lower.Prison Law",
            devolvedPowersStatus: nil,
            dpTypeOfChange: nil,
            dpReasonForChange: nil,
            dpDateOfChange: nil,
            remainderWorkFlag: nil,
            minimumCasesAllowedCount: "0",
            maximumCasesAllowedCount: "0",
            minimumToleranceCount: nil,
            maximumToleranceCount: nil,
            minimumLicenseCount: nil,
            maximumLicenseCount: nil,
            workInProgressCount: "0",
            outreach: nil,
            cancelFlag: "N",
            cancelReason: nil,
            cancelDate: nil,
            closedDate: nil,
            closedReason: nil,
          },
        ],
        nmsAuths: [],
      },
    ],
  }.to_json
end

def provider_user_json
  {
    firm: {
      firmNumber: "1639",
      firmId: 1639,
      ccmsFirmId: 19_148,
      parentFirmId: 0,
      firmName: "DAVID GRAY LLP",
      firmType: "Legal Services Provider",
      constitutionalStatus: "LLP",
      solicitorAdvocateYN: nil,
      advocateLevel: nil,
      barCouncilRoll: nil,
      companyHouseNumber: nil,
    },
    user: {
      userId: 12_345,
      ccmsContactId: 234_567,
      userLogin: "MARTIN.RONAN@DAVIDGRAY.CO.UK",
      name: "Ronan, Martin",
      emailAddress: "martin.ronan@davidgray.co.uk",
    },
  }.to_json
end

#################
# errors
#################
def stub_provider_details_retriever_record_not_found(provider:)
  stub_request(:get, "#{Rails.configuration.x.pda.url}/provider-users/#{provider.username}/provider-offices")
    .to_return(body: nil, status: 204)
end

def stub_provider_details_retriever_api_error(provider:)
  stub_request(:get, "#{Rails.configuration.x.pda.url}/provider-users/#{provider.username}/provider-offices")
    .to_return(body: "An error has occurred", status: 500)
end
