---
http_interactions:
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments
    body:
      encoding: UTF-8
      string: '{"client_reference_id":"L-4K9-MD1","submission_date":"2020-04-06","matter_proceeding_type":"domestic_abuse"}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Mon, 06 Apr 2020 16:10:57 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"afcff6ad071b912e842a582794381852"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 5c68a6e0751edc22db18156d43ff3b34
      X-Runtime:
      - '0.109229'
    body:
      encoding: ASCII-8BIT
      string: '{"success":true,"objects":[{"id":"7dfa3515-8643-45b3-8505-6a6f8acdeb47","client_reference_id":"L-4K9-MD1","remote_ip":{"family":2,"addr":1376917992,"mask_addr":4294967295},"created_at":"2020-04-06T16:10:57.894Z","updated_at":"2020-04-06T16:10:57.894Z","submission_date":"2020-04-06","matter_proceeding_type":"domestic_abuse","assessment_result":"pending"}],"errors":[]}'
    http_version: null
  recorded_at: Mon, 06 Apr 2020 16:10:57 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/7dfa3515-8643-45b3-8505-6a6f8acdeb47/applicant
    body:
      encoding: UTF-8
      string: '{"applicant":{"date_of_birth":"1992-09-16","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":false}}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Mon, 06 Apr 2020 16:10:58 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"c290336e2f3d22a7244b211f074dd727"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 65991b82cad04e455d0b2bf8f6f15006
      X-Runtime:
      - '0.011526'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":[{"id":"e6af69e5-4bd5-4216-b887-18ef7726bfaf","assessment_id":"7dfa3515-8643-45b3-8505-6a6f8acdeb47","date_of_birth":"1992-09-16","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":false,"created_at":"2020-04-06T16:10:58.073Z","updated_at":"2020-04-06T16:10:58.073Z","self_employed":false}],"errors":[],"success":true}'
    http_version: null
  recorded_at: Mon, 06 Apr 2020 16:10:58 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/7dfa3515-8643-45b3-8505-6a6f8acdeb47/capitals
    body:
      encoding: UTF-8
      string: '{"bank_accounts":[],"non_liquid_capital":[]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Mon, 06 Apr 2020 16:10:58 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"786a7e6a9cd834121a00fc4a4ad23954"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 6351e6c83d4d56159dce9b1543566fc4
      X-Runtime:
      - '0.039307'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":{"id":"6054a37e-8bb8-41dd-a80e-70da6e76315a","assessment_id":"7dfa3515-8643-45b3-8505-6a6f8acdeb47","total_liquid":"0.0","total_non_liquid":"0.0","total_vehicle":"0.0","total_property":"0.0","total_mortgage_allowance":"0.0","total_capital":"0.0","pensioner_capital_disregard":"0.0","assessed_capital":"0.0","capital_contribution":"0.0","lower_threshold":"0.0","upper_threshold":"0.0","assessment_result":"pending","created_at":"2020-04-06T16:10:57.897Z","updated_at":"2020-04-06T16:10:57.897Z"},"errors":[],"success":true}'
    http_version: null
  recorded_at: Mon, 06 Apr 2020 16:10:58 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/7dfa3515-8643-45b3-8505-6a6f8acdeb47/vehicles
    body:
      encoding: UTF-8
      string: '{"vehicles":[]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Mon, 06 Apr 2020 16:10:58 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"7eb7dee5a8f69a7b4580e1e2bd9fa86a"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 163902a555a108b0c3cf8e9867ff0c85
      X-Runtime:
      - '0.098199'
    body:
      encoding: ASCII-8BIT
      string: '{"vehicles":[],"errors":[],"success":true}'
    http_version: null
  recorded_at: Mon, 06 Apr 2020 16:10:58 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/7dfa3515-8643-45b3-8505-6a6f8acdeb47/properties
    body:
      encoding: UTF-8
      string: '{"properties":{"main_home":{"value":0.0,"outstanding_mortgage":0.0,"percentage_owned":0.0,"shared_with_housing_assoc":false},"additional_properties":[{"value":0,"outstanding_mortgage":0,"percentage_owned":0,"shared_with_housing_assoc":false}]}}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Mon, 06 Apr 2020 16:10:58 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"2ea2c7ae4c24abfd033005b9a4ea0e6d"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - cf6799b81cc7b062348e8dc47acb3807
      X-Runtime:
      - '0.086928'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":[{"id":"4d376fa0-e971-44bc-8328-209cd8d5655a","value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":true,"shared_with_housing_assoc":false,"created_at":"2020-04-06T16:10:58.695Z","updated_at":"2020-04-06T16:10:58.695Z","capital_summary_id":"6054a37e-8bb8-41dd-a80e-70da6e76315a","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","assessed_equity":"0.0","main_home_equity_disregard":"0.0"},{"id":"3f66a7ff-f0fc-436e-8c1b-e77efa61d9ce","value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":false,"shared_with_housing_assoc":false,"created_at":"2020-04-06T16:10:58.703Z","updated_at":"2020-04-06T16:10:58.703Z","capital_summary_id":"6054a37e-8bb8-41dd-a80e-70da6e76315a","transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","assessed_equity":"0.0","main_home_equity_disregard":"0.0"}],"errors":[],"success":true}'
    http_version: null
  recorded_at: Mon, 06 Apr 2020 16:10:58 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/7dfa3515-8643-45b3-8505-6a6f8acdeb47/dependants
    body:
      encoding: UTF-8
      string: '{"dependants":[]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Mon, 06 Apr 2020 16:10:58 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"27498de3719718d23b04ac9d8f287108"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 4198c6fc529b5efb76d9a556fdfcdd9c
      X-Runtime:
      - '0.004143'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":[],"errors":[],"success":true}'
    http_version: null
  recorded_at: Mon, 06 Apr 2020 16:10:58 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/7dfa3515-8643-45b3-8505-6a6f8acdeb47/state_benefits
    body:
      encoding: UTF-8
      string: '{"state_benefits":[{"name":"benefits","payments":[{"date":"2020-03-07","amount":186589.11},{"date":"2020-02-06","amount":264511.86},{"date":"2020-01-07","amount":900861.45}]}]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Mon, 06 Apr 2020 16:10:59 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"700c1bbd836e8ceb1643d35a7c126c8a"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 5dfdd811cc2a77e86c9561f4322aeb92
      X-Runtime:
      - '0.112462'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":[{"id":"874b86c5-6924-4119-8742-eb991e951451","gross_income_summary_id":"3060c52b-416f-47a7-ad02-982d497c0c5a","state_benefit_type_id":"ac07b00a-407a-439c-b42a-22b1a92cea31","name":"benefits","created_at":"2020-04-06T16:10:59.007Z","updated_at":"2020-04-06T16:10:59.007Z","monthly_value":"0.0"}],"errors":[],"success":true}'
    http_version: null
  recorded_at: Mon, 06 Apr 2020 16:10:59 GMT
- request:
    method: post
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/7dfa3515-8643-45b3-8505-6a6f8acdeb47/other_incomes
    body:
      encoding: UTF-8
      string: '{"other_incomes":[]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Mon, 06 Apr 2020 16:10:59 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"27498de3719718d23b04ac9d8f287108"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - '022981970d58f09673defe60c2d7f417'
      X-Runtime:
      - '0.006700'
    body:
      encoding: ASCII-8BIT
      string: '{"objects":[],"errors":[],"success":true}'
    http_version: null
  recorded_at: Mon, 06 Apr 2020 16:10:59 GMT
- request:
    method: get
    uri: https://check-financial-eligibility-staging.apps.live-1.cloud-platform.service.justice.gov.uk/assessments/7dfa3515-8643-45b3-8505-6a6f8acdeb47
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept:
      - application/json;version=2
      User-Agent:
      - Faraday v1.0.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty/1.15.8.2
      Date:
      - Mon, 06 Apr 2020 16:10:59 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Etag:
      - W/"068887a4fabe002c5925eb4cfabd437f"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 390f23d1d3da1c04fdfa2aa97228f2b5
      X-Runtime:
      - '0.181848'
    body:
      encoding: ASCII-8BIT
      string: '{"version":"2","timestamp":"2020-04-06T16:10:59.585+00:00","success":true,"assessment":{"id":"7dfa3515-8643-45b3-8505-6a6f8acdeb47","client_reference_id":"L-4K9-MD1","submission_date":"2020-04-06","matter_proceeding_type":"domestic_abuse","assessment_result":"contribution_required","applicant":{"date_of_birth":"1992-09-16","involvement_type":"applicant","has_partner_opponent":false,"receives_qualifying_benefit":false,"self_employed":false},"gross_income":{"monthly_other_income":"0.0","monthly_state_benefits":"450654.14","total_gross_income":"450654.14","upper_threshold":"999999999999.0","assessment_result":"eligible","state_benefits":[{"name":"benefits","monthly_value":"450654.14","excluded_from_income_assessment":false,"state_benefit_payments":[{"payment_date":"2020-03-07","amount":"186589.11"},{"payment_date":"2020-02-06","amount":"264511.86"},{"payment_date":"2020-01-07","amount":"900861.45"}]}],"other_income":[]},"disposable_income":{"outgoings":{"childcare_costs":[],"housing_costs":[],"maintenance_costs":[]},"childcare_allowance":"0.0","dependant_allowance":"0.0","maintenance_allowance":"0.0","gross_housing_costs":"0.0","housing_benefit":"0.0","net_housing_costs":"0.0","total_outgoings_and_allowances":"0.0","total_disposable_income":"450654.14","lower_threshold":"315.0","upper_threshold":"999999999999.0","assessment_result":"contribution_required","income_contribution":"315148.55"},"capital":{"capital_items":{"liquid":[],"non_liquid":[],"vehicles":[],"properties":{"main_home":{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":true,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"100000.0","assessed_equity":"0.0"},"additional_properties":[{"value":"0.0","outstanding_mortgage":"0.0","percentage_owned":"0.0","main_home":false,"shared_with_housing_assoc":false,"transaction_allowance":"0.0","allowable_outstanding_mortgage":"0.0","net_value":"0.0","net_equity":"0.0","main_home_equity_disregard":"0.0","assessed_equity":"0.0"}]}},"total_liquid":"0.0","total_non_liquid":"0.0","total_vehicle":"0.0","total_property":"0.0","total_mortgage_allowance":"100000.0","total_capital":"0.0","pensioner_capital_disregard":"0.0","assessed_capital":"0.0","lower_threshold":"3000.0","upper_threshold":"999999999999.0","assessment_result":"eligible","capital_contribution":"0.0"}}}'
    http_version: null
  recorded_at: Mon, 06 Apr 2020 16:10:59 GMT
recorded_with: VCR 5.1.0
