---
http_interactions:
- request:
    method: post
    uri: https://legal-framework-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk/merits_tasks
    body:
      encoding: UTF-8
      string: '{"request_id":"108490aa-6ea6-49a1-8756-5262b8b7db68","proceeding_types":["DA005","DA002","DA003"]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.3.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 13 Apr 2021 14:31:56 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept
      Etag:
      - W/"bc078541bc679b4e416a6eba839c5d03"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - c8e2c065acbe362646818ca52b3ec1cc
      X-Runtime:
      - '0.068102'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"request_id":"108490aa-6ea6-49a1-8756-5262b8b7db68","success":true,"application":{"tasks":{"latest_incident_details":[],"opponent_details":[],"statement_of_case":[]}},"proceeding_types":[{"ccms_code":"DA005","tasks":{"chances_of_success":[]}},{"ccms_code":"DA002","tasks":{"chances_of_success":[]}},{"ccms_code":"DA003","tasks":{"chances_of_success":[]}}]}'
  recorded_at: Tue, 13 Apr 2021 14:31:56 GMT
recorded_with: VCR 6.0.0
