name: Check anonymise rules
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  check-anonymise-rules:
    name: Check anonymise rules
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5 # v1.301.0
      - name: Setup Faker
        run: gem install faker
      - name: Run check
        run: ./scripts/migration_hook.rb
