name: Check anonymise rules
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  check-anonymise-rules:
    name: Check anonymise rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      - name: Setup Faker
        run: gem install faker
      - name: Run check
        run: ./scripts/migration_hook.rb
