name: "Generate apply-base docker image"
on:
  schedule:
    - cron:  '45 5 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
      - name: Build the Docker image
        run: |
          docker build . --file ./docker/apply_base.dockerfile --tag ministryofjustice/apply-base:latest --tag ministryofjustice/apply-base:latest-$(cat .ruby-version)
      - name: Push the Docker image
        run: |
          docker push ministryofjustice/apply-base:latest
          docker push ministryofjustice/apply-base:latest-$(cat .ruby-version)
      - name: Slack Notification on failure to apply-devtest channel
        if: failure()
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c #v3.0.3
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": 'G9FJZ8H17',
              "text": "GitHub apply-base docker image Action build result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub apply-base docker Action build result: ${{ job.status }}\nAn error occurred while generating the apply-base docker image"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
