# This workflow integrates Brakeman with GitHub's Code Scanning feature
# Brakeman is a static analysis security vulnerability scanner for Ruby on Rails applications

name: Brakeman Scan

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  brakeman:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/brakeman.yml@da8dfead60c43877af5a5e72ffa8c72301cac18f # main as of 12/06/2026
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
