name: "Generate apply-ci docker image"
on:
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Build the Docker image
        run: |
          docker build . --file ./docker/apply_ci.dockerfile --tag ministryofjustice/apply-ci:latest --tag ministryofjustice/apply-ci:latest-$(cat .ruby-version)
      - name: Push the Docker image
        run: |
          docker push ministryofjustice/apply-ci:latest
          docker push ministryofjustice/apply-ci:latest-$(cat .ruby-version)
      - name: Slack Notification on failure to apply-devtest channel
        if: failure()
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 #v3.0.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": 'G9FJZ8H17',
              "text": "GitHub apply-ci docker image Action build result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub apply-ci docker Action build result: ${{ job.status }}\nAn error occurred while generating the apply-ci docker image"
                  }
                }
              ]
            }
