name: Create Jira Ticket

on:
  pull_request:
    types:
      - opened

jobs:
  create_jira_ticket:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') }}

    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira Ticket
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: AP
          issuetype: Maintenance
          summary: "Dependabot PR in ${{ github.repository }}: ${{ github.event.pull_request.title }}"
          description: ${{ github.event.pull_request.body }}
