name: Static Application Security Testing
on:
  schedule:
    - cron:  '15 6 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  run-sast-tooling:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/sast.yml@a0bd8225ca8cc96e57a19223ce21f2ce7230833c # main as of 24/06/2026
    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read
    with:
      image_uri: ${{ format('{0}:latest', vars.ECR_REGISTRY_URI) }}
    secrets:
      SNYK_CLIENT_ID: ${{ secrets.SNYK_CLIENT_ID }}
      SNYK_CLIENT_SECRET: ${{ secrets.SNYK_CLIENT_SECRET }}
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
